### ISSUE TITLE
Can this run on a local machine?

### ISSUE THREAD

**Issue by btsimonh** [lambci/docker-lambda#10]
when running create_build, yum fails on access to the amazonaws repos with "The requested URL returned error: 403 Forbidden".
After lots of reading, I think these repos are off-limits for anyone NOT running in EC2.

Anyone got the build to work on a local machine?

Note: this question came from a total noob to docker - you don't NEED to build it to use it.... if happy with the content you can just run the image, and docker will download a pre-built one. 
i.e. just run 
docker run -it lambci/lambda:build bash
and within a couple of minute, you will have a terminal session with gcc installed.

**Comment by mhart** [comment]
@btsimonh right, the `build` images come with gcc and a whole host of things already installed for you – see the bottom of the README: https://github.com/lambci/docker-lambda#documentation

As you say, you need to be running on an EC2 machine to be able to install new packages.
