### ISSUE TITLE
"KeyError","Unable to parse", What  should the lambda_function json format be? 

### ISSUE THREAD

**Issue by jeremyzhou** [lambci/docker-lambda#101]
How do I write a correct json body of lambda function?

first time:
[root@localhost backend]# docker run --rm -v /home/jlzhou/cloud/create_org/:/var/task  -e MONGO_DB_NAME=ezmcloud -e MONGO_USER=jeremy -e MONGO_PASSWORD=123 -e MONGO_HOST=172.18.0.11 docker.io/lambci/lambda:python2.7 lambda_function.create_org '{"name":"test2","description":"test2","photo_url":""}'
START RequestId: c081c875-e9b3-41d4-ac01-3e51ceef2eba Version: $LATEST
'body': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 15, in create_org
    body = event["body"]
KeyError: 'body'

END RequestId: c081c875-e9b3-41d4-ac01-3e51ceef2eba
REPORT RequestId: c081c875-e9b3-41d4-ac01-3e51ceef2eba Duration: 119 ms Billed Duration: 200 ms Memory Size: 1536 MB Max Memory Used: 15 MB

{"stackTrace": [["/var/task/lambda_function.py", 15, "create_org", "body = event[\"body\"]"]], "errorType": "KeyError", "errorMessage": "'body'"}

second time:
[root@localhost backend]# docker run --rm -v /home/jlzhou/cloud/create_org/:/var/task  -e MONGO_DB_NAME=ezmcloud -e MONGO_USER=jeremy -e MONGO_PASSWORD=123 -e MONGO_HOST=172.18.0.11 docker.io/lambci/lambda:python2.7 lambda_function.create_org '"body":{"name":"test2","description":"test2","photo_url":""}'
START RequestId: 34dbdbe8-4aff-4399-bf00-19ab92fc9d8f Version: $LATEST
Unable to parse input as json: Extra data: line 1 column 7 - line 1 column 61 (char 6 - 60)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 7 - line 1 column 61 (char 6 - 60)

END RequestId: 34dbdbe8-4aff-4399-bf00-19ab92fc9d8f
REPORT RequestId: 34dbdbe8-4aff-4399-bf00-19ab92fc9d8f Duration: 104 ms Billed Duration: 200 ms Memory Size: 1536 MB Max Memory Used: 15 MB

{"stackTrace": [["/usr/lib64/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 367, "decode", "raise ValueError(errmsg(\"Extra data\", s, end, len(s)))"]], "errorType": "ValueError", "errorMessage": "Extra data: line 1 column 7 - line 1 column 61 (char 6 - 60)"}

**Comment by jeremyzhou** [comment]
[root@localhost backend]# docker run --rm -v /home/jlzhou/cloud/create_org/:/var/task  --env MONGO_DB_NAME=ezmcloud --env MONGO_USER=jeremy --env MONGO_PASSWORD=123 --env MONGO_HOST=172.18.0.11 docker.io/lambci/lambda:python2.7 lambda_function.create_org '{"body":{"name":"test2","description":"test2","photo_url":"www.baidu.com"}}'
START RequestId: 77567eb2-eb9e-4faf-8bc0-f04bbe5a2729 Version: $LATEST
expected string or buffer: TypeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 19, in create_org
    body_json = json.loads(body)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

END RequestId: 77567eb2-eb9e-4faf-8bc0-f04bbe5a2729
REPORT RequestId: 77567eb2-eb9e-4faf-8bc0-f04bbe5a2729 Duration: 119 ms Billed Duration: 200 ms Memory Size: 1536 MB Max Memory Used: 15 MB

{"stackTrace": [["/var/task/lambda_function.py", 19, "create_org", "body_json = json.loads(body)"], ["/usr/lib64/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 364, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"]], "errorType": "TypeError", "errorMessage": "expected string or buffer"}

**Comment by mhart** [comment]
It needs to be valid JSON. This is not valid JSON:

```
"body":{"name":"test2","description":"test2","photo_url":""}
```

You probably meant:

```
{"body":{"name":"test2","description":"test2","photo_url":""}}
```

**Comment by jeremyzhou** [comment]
It had been solved. Valid json body should be '{"body":{"name":"test2","description":"test2","photo_url":""}}'.
But another question,lambda function source code to decode json body:
    body = event["body"]
    if body is None:
        return Response.response_message(Statuscode.BadRequest, ResponseMessages.InvalidBody)
    body_json = json.loads(body)

But result is:
[root@localhost backend]# docker run --rm -v /mnt/hgfs/ShareFolder/lambda/functions/create_user/:/var/task  -e MONGO_DB_NAME=ezmcloud -e MONGO_USER=jeremy -e MONGO_PASSWORD=123 -e MONGO_HOST=mongodb -e COGNITO_IDENTITY_POOL_ID=1 -e COGNITO_USER_POOL_ID=1 -e COGNITO_USER_POOL_CLIENT_ID=1 --net TestNet --ip 172.18.0.20 --link=mongo:mongodb docker.io/lambci/lambda:python2.7 lambda_function.create_user '{"body":{"name":"jeremy","email":"jlzhou@sonicwall.com","password":"testabcde","family_name":"zhou","given_name":"lei","company":"sonicwall","mobile":"15900739939"}}'
START RequestId: c341290a-66f7-4cc8-be7f-8b9496e9fe8a Version: $LATEST
expected string or buffer: TypeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 31, in create_user
    body_json = json.loads(body)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

END RequestId: c341290a-66f7-4cc8-be7f-8b9496e9fe8a
REPORT RequestId: c341290a-66f7-4cc8-be7f-8b9496e9fe8a Duration: 373 ms Billed Duration: 400 ms Memory Size: 1536 MB Max Memory Used: 20 MB

{"stackTrace": [["/var/task/lambda_function.py", 31, "create_user", "body_json = json.loads(body)"], ["/usr/lib64/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 364, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"]], "errorType": "TypeError", "errorMessage": "expected string or buffer"}

So I have to change some code below:
body = event["body"]
    if body is None:
        return Response.response_message(Statuscode.BadRequest, ResponseMessages.InvalidBody)
    json_string=json.dumps(body)
    print(json_string) 
    body_json = json.loads(json_string)
    if not isinstance(body_json, dict):
        return Response.response_message(Statuscode.BadRequest, ResponseMessages.InvalidBody)
    print(body_json)
    name = body_json.get("name")

And it works. what 's the difference between two decode ways?

**Comment by mhart** [comment]
I'm really not sure what you're asking here. This question really depends on what sort of event you're trying to send to your lambda. The event itself has to be in JSON. The properties of that JSON can be anything you like (eg, `body`, etc)

If you're trying to simulate an API Gateway event specifically, then the `body` needs to be a string, like:

```
{"body": "this is my body"}
```

Or:

```
{"body": "{\"this\":\"is a JSON string\"}"}
```

I'm going to close this because it's not an issue with `docker-lambda`
