### ISSUE TITLE
Lambda Memory Size is Not Used When Running JVM

### ISSUE THREAD

**Issue by jaimm** [lambci/docker-lambda#102]
The Max Heap Size for the JVM is currently hardcoded to be an arbitrary size of ~1.3GB. This means that if your function needs to use more than that, you can encounter OutOfMemoryErrrors in Docker, even though you don't when the function is running in Lambda
https://github.com/lambci/docker-lambda/blob/a6feafdf570f7b9ba2c71272e7d2ce917e49d26f/java8/run/Dockerfile#L20

Would it be possible to instead use AWS_LAMBDA_FUNCTION_MEMORY_SIZE?

**Comment by mhart** [comment]
I used the value that was being used in production Lambda directly – it may have changed now that 3GB functions are allowed.

What's the value you're seeing on Lambda itself?

**Comment by mhart** [comment]
Have fixed this in f5241cfe5ee81c149d3de077b74afee1f609ea45 – thanks for alerting me!

Should be pushed up soon
