### ISSUE TITLE
Make /var/task writable for sbx_user1051

### ISSUE THREAD

**Issue by TorstenF76** [lambci/docker-lambda#103]
Could you make /var/task writable for the current user (`sbx_user1051`)?

We'd like to use `lambci/lambda:go1.x` in a gitlab-ci job as image, where we cannout mount any directories as we do not have control over the docker run command. But if we could just copy our file into the /var/task dir, that would be fine. 

We'd override the entrypoint at startup and start the original entrypoint manually after the copy job. 
See https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#available-settings-for-image 

I could imagine that it would just be enough to add the following command here: https://github.com/lambci/docker-lambda/blob/master/base/Dockerfile#L22

`RUN chown sbx_user1051:495 /var/task`

If the current owner `slicer` does matter, it would also be OK to grant write access to everyone or at least a common group of these users. 

Thank you very much!

**Comment by mhart** [comment]
No, the current user doesn't have access to `/var/task` on Lambda – only `/tmp` (and this docker image is intended to replicate the lambda environment)

**Comment by mhart** [comment]
Maybe you want to look at the build images if you're using this in CI? (ie, `lambci/lambda:build-go1.x`)

**Comment by TorstenF76** [comment]
Thanks for the quick response. I did not get into the build images, I juse made an intermediade Dockerfile adding write access for all. Quick and easy for my needs :-)

keep up the good work! :+1:

**Comment by jackmcguire1** [comment]
@TorstenF76 how was this achieved, as according to a lot of users, they're struggling to get debugging working due to 
`Could not create config directory: mkdir /home/sbx_user1051: permission denied.API server listening at: [::]:5986`

https://github.com/awslabs/aws-sam-cli/issues/1067

**Comment by mhart** [comment]
@jackmcguire1 that message looks like just a warning – that shouldn't be preventing you from debugging – as this comment says delve will just fallback to a default config: https://github.com/awslabs/aws-sam-cli/issues/1067#issuecomment-499135997
