### ISSUE TITLE
Interactive shell

### ISSUE THREAD

**Issue by mfulton26** [lambci/docker-lambda#104]
I want to build something on the AWS Lambda image (specifically an .so file for python 3.6).

I can't seem to figure out how to drop into an interactive shell though:

```bash
docker run -v $(pwd):/code -it --rm lambci/lambda-base:raw
```

```
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

I'm new to docker and I'm probably missing something obvious. Help would be greatly appreciated.

**Comment by mhart** [comment]
You probably want the `build` images, specifically `lambci/lambda:build-python3.6`

The README has a bunch of examples

**Comment by mfulton26** [comment]
Thank you for the reply. I very much appreciate it. I'm thinking i'm still missing something.

e.g. The following drops me into a bash shell:

```bash
docker run -v $(pwd):/code -it --rm amazonlinux
```

But the following doesn't:

```bash
ocker run -v $(pwd):/code -it --rm lambci/lambda:build-python3.6
```

And here's the output I get:

```
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

So I guess what I don't know is why `lambci/lambda:build-python3.6` doesn't have a default command to open a shell or something.

Any ideas? Thanks.

**Comment by mfulton26** [comment]
I looked in the readme for anything like this and all I see is running code in the lambda but I want to actually playing around on the lambda-like instance.

**Comment by mfulton26** [comment]
Oops. I found it:

```bash
docker run -it lambci/lambda:build-python3.6 bash
```

And that works for me. Thanks!
