### ISSUE TITLE
Proper way to incorporate other docker dependencies like a database?

### ISSUE THREAD

**Issue by JacobWeyer** [lambci/docker-lambda#111]
Ex. I need to receive data, use it to query something from mysql, then insert into DynamoDB.

I'm familiar with setting up a docker-compose file but not sure how to fit the lambda function itself into my configuration. 

Do you have any recommendation for setting this up to test other dependencies together or should I just `docker-compose up -d` Mysql and Dynamo and then run my tests by doing mocha with the `docker-lambda` package locally?

**Comment by mozey** [comment]
I prefer to run each dependency in it's own docker container with some bash scripts to setup, some notes about this approach can be found in my [aws-local](https://github.com/mozey/aws-local) repos.

An all in one solution would be to use [localstack](https://github.com/localstack/localstack)

I suspect what you are asking out of scope for this repos

**Comment by JacobWeyer** [comment]
Yeah, this repo worked really well at running one off lambdas but getting
it altogether in a single docker-compose doesn't seem easily feasible
