### ISSUE TITLE
python3.6 cannot import local modules

### ISSUE THREAD

**Issue by Caian** [lambci/docker-lambda#114]
Greetings! Like some users here, I am trying to test a Django project packaged with Zappa.

I have uncompressed the zip generated by Zappa into a `project` directory, it contains all the extra modules inside it, in the root of the directory.

Bu then I run the docker using `docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 handler.lambda_handler` I get the following error:

```
START RequestId: 7380e309-335a-4c2c-8dd1-1ef73f161eea Version: $LATEST
Unable to import module 'handler': No module named 'werkzeug.wrappers'
END RequestId: 7380e309-335a-4c2c-8dd1-1ef73f161eea
REPORT RequestId: 7380e309-335a-4c2c-8dd1-1ef73f161eea Duration: 107 ms Billed Duration: 200 ms Memory Size: 1536 MB Max Memory Used: 24 MB

{"errorMessage": "Unable to import module 'handler'"}
```

It appears that the container is failing to find the module `werkzeug.wrappers` in the root of the project.

I am able to successfully run the handler from my interpreter (Miniconda 3.6):

```
python -c 'import handler
handler.lambda_handler(None,None)'
```

Here are the full contents of the directory:

```
argcomplete
argcomplete-1.9.3.dist-info
base58.py
boto3-1.8.6.dist-info
botocore-1.11.6.dist-info
certifi
certifi-2018.8.24.dist-info
cfn_clean
cfn_flip
cfn_tools
chardet
chardet-3.0.4.dist-info
click
click-6.7.dist-info
db.sqlite3
django
Django-2.1.1.dist-info
django_test
django_zappa_app.py
durationpy
easy_install.py
future
future-0.16.0.dist-info
handler.py
hjson
idna
idna-2.7.dist-info
__init__.py
jmespath
jmespath-0.9.3.dist-info
kappa
lambda_packages
libfuturize
libpasteurize
manage.py
package_info.json
past
pip-9.0.3.dist-info
pkg_resources
placebo
__pycache__
python_dateutil-2.6.1.dist-info
python_slugify-1.2.4.dist-info
pytz
pytz-2018.5.dist-info
requestlogger
requests
requests-2.19.1.dist-info
s3transfer-0.1.13.dist-info
setuptools
setuptools-39.0.1.dist-info
six-1.11.0.dist-info
six.py
slugify
_sqlite3.so
toml.py
tqdm
tqdm-4.19.1.dist-info
troposphere
unidecode
Unidecode-1.0.22.dist-info
urllib3
urllib3-1.23.dist-info
werkzeug
Werkzeug-0.14.1.dist-info
wheel
wheel-0.31.1.dist-info
yaml
zappa
zappa_settings.json
zappa_settings.py
```

Thanks,

Caian

**Comment by dargor** [comment]
I also bumped into this because of my (restrictive) umask, you can just set `0711` on directories and `0644` on files from the root of your project.

**Comment by mhart** [comment]
@Caian `/var/task` deliberately has the same restrictive permissions as on the live Lambda environment – if you can't read subdirectories, then that's probably a local permission issue (eg, umask as @dargor suggested)

**Comment by izhangzhihao** [comment]
Hi, I'm just seen this error
```
Failed to write to log, write a: bad file descriptor
```
By doing almost the same things in python 3.7:

```sh
docker run -v "$PWD":/var/task lambci/lambda:build-python3.7 /bin/sh -c "pip install -r requirements.txt -t libs;cp /var/rapid/init /var/runtime/init;/var/runtime/init --bootstrap /var/runtime/bootstrap"
```

Did anyone know how to fix this?
