### ISSUE TITLE
Support for context.function_name

### ISSUE THREAD

**Issue by aniecki** [lambci/docker-lambda#118]
Somehow this defaults to string  ":test". So the arn print would be (as an example)
arn:aws:lambda::eu-west-1:104260451092:function:test. 
Now if I try to use it as a call parameter it will fail with ResourceNotFoundException error as there is no such function, called test.. Not sure, how to overcome it...

**Comment by mhart** [comment]
Try running and setting the `AWS_LAMBDA_FUNCTION_NAME` env variable. (eg, `docker run -e AWS_LAMBDA_FUNCTION_NAME=my-function ...`)

**Comment by aniecki** [comment]
Thanks. 

Now indeed a progress, though I am surprised, as it will run aws account lambda! 
But - how to reference (the function name?)  the locally invoked lambda function, so it will call itself again. 
Will it be a name as a copy of a handler file - in my case name (name.py)?

**Comment by mhart** [comment]
I'm not sure what you mean, sorry. You want the lambda to call itself? If you want to test that locally you'll need to use something like https://github.com/awslabs/aws-sam-cli – you won't be able to do it using docker only

**Comment by aniecki** [comment]
Ok, if this can be done by only sam I will experiment with this aws sam
