### ISSUE TITLE
Base the image FROM the official Amazon Linux docker image

### ISSUE THREAD

**Issue by jghaines** [lambci/docker-lambda#12]
AWS have published a Docker Image for Amazon Linux. It's available via ECR. I don't (yet?) see it on hub.docker.com

I assume this would be a closer base image than whatever is currently used.

https://aws.amazon.com/blogs/aws/new-amazon-linux-container-image-for-cloud-and-on-premises-workloads/

**Comment by mhart** [comment]
There is no base image currently used – it's a raw tar import.

Amazon Linux has a number of differences w/ Lambda – quite a number of files differ, as well as extra and missing packages – it would be much more work to determine what they all are, and I can't see any real benefit.

I looked at basing it off Amazon Linux in the first place (by constructing my own Amazon Linux image), but the differences were just too numerable.

I'm going to close this – but if you'd like to open a PR that does this I'd be more than happy to consider it if there's some benefit 👍
