### ISSUE TITLE
docker-lambda vs docker/amazonlinux

### ISSUE THREAD

**Issue by mc962** [lambci/docker-lambda#122]
I came across this through a link from AWS SAM, and I was definitely intrigued with something that advertises specifically as being tailored to Lambda.

Right now we use an image from [amazonlinux](https://hub.docker.com/_/amazonlinux/) for similar purposes as docker-lambda. I'm curious if there are any differences/benefits to using docker-lambda over the amazonlinux image.

From reading about `Amazon Linux` that amazonlinux was built off of, I would guess that an `amazonlinux` image would focus more on modeling an EC2 environment, while `docker-lambda` would focus more on modeling a Lambda environment. But I'm curious if there are any significant benefits to using docker-lambda over amazonlinux that would justify a switch (and if so, it might be useful to explicitly mention that in the FAQ of the README). After giving it another read I guess it's sort of explained in the second bullet point, but I wanted to confirm the differences.

**Comment by mhart** [comment]
The Lambda environment isn't exactly the same as a stock-standard Amazon Linux image. It's based on it, but it has some more packages, some less packages, some different directories, etc.

The main benefits are that docker-lambda is much closer to the Lambda filesystem (and permissions) than Amazon Linux
