### ISSUE TITLE
Release new lambda image - Two important changes

### ISSUE THREAD

**Issue by mooyoul** [lambci/docker-lambda#123]
There's new updates to lambda:

1. Now lambda supports function execution up to 15 minutes!
2. Now Node.js 8.10 Runtime supports any Promise implementations! (Relevant Issue: https://github.com/aws/aws-xray-sdk-node/issues/27)

**Comment by mhart** [comment]
@mooyoul the images already support arbitrary execution times. Set the `AWS_LAMBDA_FUNCTION_TIMEOUT` env variable to whatever you'd like. I'll probably keep the default at 300 seconds so that it doesn't break any existing users expectations.

Updating the nodejs8.10 image now

**Comment by mhart** [comment]
Done – thanks for the heads up! 👍

**Comment by mooyoul** [comment]
@mhart Thank you for your effort as always! 💯
