### ISSUE TITLE
Unable to access hosted API (localhost) in docker-lambda

### ISSUE THREAD

**Issue by prakash159753** [lambci/docker-lambda#124]
I have hosted a API in linux environment using SAM CLI at 127.0.0.1:3000. I want to test the server API (127.0.0.1:3000) using lambda function.

I have tested the server API using node JS program (node <programname.js>). But, when I am modifying the same program as lambda function and running in docker, it is throwing connection error.
The lambda function is unable to access the local host (127.0.0.1:3000) using docker. Refer to the below docker command:
docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 index.myHandler '{"some": "event"}'

**Comment by mhart** [comment]
I don't think this is a bug with `docker-lambda` – you might just need to get up to speed with how networking works in docker: https://docs.docker.com/network/

**Comment by prakash159753** [comment]
@mhart - Thanks for sharing such a great work. I tested several lambda functions using the docker-lambda command. 
I am not sure the issue is related with docker-lambda bug. But, the lambda function which require to connect the localhost (127.0.0.1:3000)  is facing the connection error.
docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 index.myHandler '{"some": "event"}'
