### ISSUE TITLE
Publish image for lambda's new python 3.7 runtime

### ISSUE THREAD

**Issue by softprops** [lambci/docker-lambda#132]
Hot of the presses https://aws.amazon.com/blogs/compute/python-3-7-runtime-now-available-in-aws-lambda/

**Comment by softprops** [comment]
I'm guessing this would need a new dumper. Something like [this](https://github.com/lambci/docker-lambda/blob/master/base/dump-python36.py)

**Comment by mhart** [comment]
Done in https://github.com/lambci/docker-lambda/commit/113c2ddd26f39cab2ce814197705df90713e32cf
