### ISSUE TITLE
Support Custom Lambda Runtime

### ISSUE THREAD

**Issue by mooyoul** [lambci/docker-lambda#135]
[Now Lambda officially supports "Custom Runtime"](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-lambda-now-supports-custom-runtimes-and-layers/), which enables polyglot lambda functions! (e.g. Node.js 11 Runtime, Rust Runtime, etc...)

Lambda Developer Documentation was updated also :)
Please refer technical details on below links:
- [AWS Lambda Developer documentation - Custom Runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html)
- [AWS Lambda Developer documentation - Lambda Runtime Interface](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html)
- [AWS Lambda Developer documentation - Tutorial – Custom Runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html)

**Comment by mhart** [comment]
Please read the README, support for this was already added in https://github.com/lambci/docker-lambda/commit/98c67ee92cf6720b87be39f92283e846653ee45e

**Comment by mooyoul** [comment]
Ah, just saw your tweet. Thanks for your effort! Thanks ❤️

**Comment by mooyoul** [comment]
BTW committed 5 days ago? how did you know that? Do you have time machine? 🤣

**Comment by mhart** [comment]
Let's just say I had a heads up 😉
