### ISSUE TITLE
Support additional args in containers based on Provided Runtime

### ISSUE THREAD

**Issue by jfuss** [lambci/docker-lambda#138]
For images that are based on the Provided runtime (Ruby2.5 and Python3.7), there is no way to add additional arguments to the language. An example of this would be starting up another module for debugging in Python. 

This was possible in previous runtime containers since the entrypoint was using the runtime directly (https://github.com/lambci/docker-lambda/blob/master/python3.6/run/Dockerfile#L15). In the case of Python3.7 and Ruby2.5's, the runtime is being started through the init.go, which calls the bootstrap file. Without a way to add additional arguments, SAM CLI is unable to support debugging Python3.7 and Ruby2.5. 

Proposals:
1. Add a flag into the init.go binary that would allow adding additional arguments
1. Create a debug-init.go that can be called when additional arguments are passed.

I not really sure which one is better or if there are other options that could be implemented that would allow this support.

Thoughts?

**Comment by mhart** [comment]
Hey, sorry I don't really have time to explore this – but would be more than happy to accept a PR or two exploring these ideas.

The `init` binary already takes a `bootstrap` argument that we could override with a custom bootstrap file that we could include on whatever runtime we wanted. But I don't know enough about the debugging requirements for ruby, python, etc to know if that would cover it?

**Comment by awood45** [comment]
For Ruby, we basically just need an open port for `Byebug.remote_byebug` to open a local server. Probably don't need more than that at this point.

**Comment by abrooksv** [comment]
Ruby mine details https://www.jetbrains.com/help/ruby/remote-debugging.html

**Comment by mhart** [comment]
Should be fixed by https://github.com/lambci/docker-lambda/pull/172
