### ISSUE TITLE
Incorrect permissions using build-nodejs8.10 and Lerna

### ISSUE THREAD

**Issue by g-sam** [lambci/docker-lambda#139]
After running `lerna bootstrap` installed executables in some packages (typically 1 or 2 of 15) are sometimes missing execute permissions. The behaviour does not always occur and different packages are affected on different runs (same lockfiles).

```
bash-4.2# ls -l package1/node_modules/serverless/bin/serverless
-rwxr-xr-x 1 root root 1983 Dec  7 13:00 package1/node_modules/serverless/bin/serverless
bash-4.2# ls -l  package2/node_modules/serverless/bin/serverless
-rw-r--r-- 1 root root 1908 Dec  7 13:01  package2/node_modules/serverless/bin/serverless
```

 Is this a bug or have we set something up incorrectly?

**Comment by mhart** [comment]
No idea – there's nothing specific in this image that could cause that, but it might be a generic Docker bug of some kind

**Comment by g-sam** [comment]
We were previously using `circleci/node:10.10.0-browsers-legacy` which uses a non root user and did not have this issue. Seems like it might be something to do with the combination of running as root, the unsafe-permission flag, and Lerna 🤷‍♂️ .

**Comment by mhart** [comment]
This seems to be something specific to a Docker environment setup – I don't believe it's an issue to do with anything in this image per se
