### ISSUE TITLE
Building with NPM package.

### ISSUE THREAD

**Issue by j** [lambci/docker-lambda#140]
You can invoke lambda from the node package, but it would be nice to be able to build too.

**Comment by mhart** [comment]
Can you give me an example of what you mean?

**Comment by j** [comment]
@mhart 

```javascript
buildResult = dockerLambda({ dockerImage: 'lambci/lambda:build-nodejs8.10' });
```

So, building via node instead of invoking as lambda function.

**Comment by j** [comment]
Also, @mhart can I pass NPM_TOKEN to build-node* images?  I can't get my private scoped packages to resolve (404)

**Comment by mhart** [comment]
Yep, you can use `docker -e NPM_TOKEN=<my-token> ...` – check the docker docs for details

**Comment by j** [comment]
Sorry, I thought NPM_TOKEN wasn't passed down to the actual container somehow through my testing.

**Comment by mhart** [comment]
Not going to implement this – I don't really see a use case here – the dockerLambda function is intended to get the output of a lambda invocation and the build images aren't intended for this.

To actually perform a build from Node.js, it's trivial to just do `child_process.execSync('docker run ... lambci/lambda:build-nodejs8.10')`
