### ISSUE TITLE
Should PYTHONPATH include /opt/python (etc.) for layer support?

### ISSUE THREAD

**Issue by mojodna** [lambci/docker-lambda#144]
Per https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html, the Python runtimes look in `/opt/python` and `/opt/python/lib/python<version>/site-packages`. Out of the box, `PYTHONPATH=/var/runtime`(for `build-python3.6`, anyway; it's empty for `python3.6`, should it be?).

Should `PYTHONPATH` include the listed site directories to configure `pip[3]` (in which case layered packages will show up in `pip freeze` and serve as already-installed dependencies) and `python`?

**Comment by mhart** [comment]
It's empty for `python3.6` because the bootstrap adds those directories to the path at runtime.

So any code should work on `python3.6` as it does on Lambda.

Have you run into any issues here?

**Comment by mojodna** [comment]
Ah, I was guessing as much, thanks!

For the build variant, I was looking ahead to building an app against a layer, so having it in the environment would make installing packages from pip work as expected, rather than installing duplicates.

**Comment by mhart** [comment]
I would look into using [`sam build`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) for this (or alternatively https://github.com/brysontyrrell/Possum ) – they both use these images under the hood, but manage the complexity .

I don't really want to mess with env vars too much in the images themselves in case ppl rely on them being the same as in production

**Comment by mojodna** [comment]
Makes sense, thanks for the pointers!!

**Comment by mdavis-xyz** [comment]
Can someone clarify the workaround here?
If I want to `import somelib` from a python module installed like a lambda layer with `pip install --target /opt/python`,
and I want to do this during a Dockerfile `RUN python ...` command,
do I just need to add:

```
ENV PYTHONPATH=$PYTHONPATH:/opt/python:/opt/python/lib/python{{ python_version }}/site-packages
```

To the Dockerfile?

**Comment by doug65536** [comment]
It doesn't find modules in `/opt` for me. I made a response handler dump env and /opt, and the PYTHONPATH never had anything except '/var/runtime', at runtime! So your assertion that it adds it at runtime is false, for me. I have wasted a lot of time trying to believe the layer docs that say `/opt/python` works.
