### ISSUE TITLE
Running with sam local having issues with post and some get methods

### ISSUE THREAD

**Issue by kappaj2** [lambci/docker-lambda#146]
I'm running sam local with a Java8 Spring Lambda function on Macbook Pro. 

When I deploy to AWS cloud, the post method body is fine, can log details in CloudWatch.
A GET method with @RequestParamter also works fine.

Running $ sam local start-api
Call api end-point with Postman GET:
The RequestParameter values stay null, simply can't get this to get populated.

Call api end-point with Postman POST:
Throws octet stream not supported.
This happens on all the developer machines we have.

Anybody seen anything like this before?

**Comment by mhart** [comment]
This seems to be an issue to post over at https://github.com/awslabs/aws-sam-cli
