### ISSUE TITLE
Unable to run mktemp in lambci/lambda:provided image

### ISSUE THREAD

**Issue by nadirsidi** [lambci/docker-lambda#148]

**Comment by mhart** [comment]
Just confirming – you can run this on Lambda?

**Comment by nadirsidi** [comment]
Hello, thank you for all your work in putting together these images. They are an excellent resource for developing against Lambda locally.

I am trying to run the AWS quickstart for the custom runtime and when the bootstrap file is run the mktemp to capture the header information from the runtime API is causing the error:

`mktemp: failed to create file via template ‘/tmp/tmp.XXXXXXXXXX’: Permission denied`

**Comment by nadirsidi** [comment]
This is a repo with the code taken from the AWS quickstart that I'm trying to run. I was seeing this issue with a bootstrap file for an R runtime I built, and then realized I was seeing the same issue when I went back to try and run this tutorial. Not sure what's different, but I believe I had initially run the tutorial with the `lambci/lambda:provided` image on my work Mac, now I'm on my personal Ubuntu machine.

**Comment by nadirsidi** [comment]
https://github.com/nadirsidi/aws-runtime-tutorial.git

**Comment by mhart** [comment]
Works for me:

```console
$ docker run --rm --entrypoint bash lambci/lambda:provided -c 'mktemp && ls /tmp'
/tmp/tmp.Jbq5HqnB0p
tmp.Jbq5HqnB0p
```

**Comment by mhart** [comment]
Probably an issue with the Docker use you're using?

**Comment by nadirsidi** [comment]
Alright, thank you for confirming. I'll troubleshoot my Docker set-up. I appreciate your quick response!

**Comment by mhart** [comment]
Going to close this as I believe it's an issue with your Docker setup and not this image
