### ISSUE TITLE
Unable to bootstrap file on lambci/lambda:provided when task contains a folder called "bootstrap"

### ISSUE THREAD

**Issue by footballencarta** [lambci/docker-lambda#152]
As the title says, I'm unable to run custom Lambda layers (that contain the bootstrap file), as the task contains a bootstrap folder.

This results in "Error: fork/exec /var/task/bootstrap: permission denied" - once the bootstrap folder has been renamed - this then worked as expected, and replicates the behaviour seen in AWS Lambda.

I should note also, that the same code has been running on AWS lambda with the same layers (and the folder existing in the task called bootstrap) with no issues. The issues seem to be with the docker container.

I believe the issue might lie around here (https://github.com/lambci/docker-lambda/blob/master/provided/run/init.go#L104 - I would PR, but I've got zero experience with Go.) - could this be fixed to replicate the behaviour of Lambda please?

Thanks

**Comment by mhart** [comment]
So you've got `/var/task/bootstrap` that's a directory – and then I presume you have `/opt/bootstrap` in one of your other layers? Or how are you bootstrapping the provided runtime?

**Comment by footballencarta** [comment]
That’s correct - yes.

**Comment by mhart** [comment]
Fixed in https://github.com/lambci/docker-lambda/commit/f48ff1f07a3a1a24c4ab04414c3844cb8c8642d9 – thanks for reporting this!
