### ISSUE TITLE
Permissions not matching AWS

### ISSUE THREAD

**Issue by wmertens** [lambci/docker-lambda#159]
I spent quite some time figuring out that an npm module was getting installed with no read permissions for "other" which meant that the AWS Lambda couldn't load the module. For future reference, the error was

    module initialization error: Error

without any more detail. I had to patch `require` to find the problematic module.

My guess is that the Lambda function code is not owned by the user running `node`. It would be great if the dockder image could replicate this.

**Comment by mhart** [comment]
Have you tried matching the permissions in `/var/task` exactly? To do this you'll need to run from a Dockerfile like this example: https://github.com/lambci/docker-lambda/blob/master/examples/docker-file/Dockerfile#L11-L14 – there's no (simple) way to just do this from `docker run` when you're mounting a volume

**Comment by wmertens** [comment]
Aha that should indeed do the trick. I think this should be mentioned in the readme.

**Comment by wmertens** [comment]
actually, I can reproduce my issues quite easily by just adding `:ro` to the task mount :) I'll PR a change to the readme
