### ISSUE TITLE
'file' and 'file-libs' packages are downgraded in build images

### ISSUE THREAD

**Issue by njv299** [lambci/docker-lambda#168]
The 'file' and 'file-libs' packages in the `build-python3.6` image are downgraded to version 5.22. The main AMI images run (as of 02/15/2019) version 5.30. This causes incompatibility in compiled magic files that are generated in a build-python3.6 container. 

I suspect that one of the packages being added to the `build` version forces a downgrade, but have not found conclusive proof.

To verify the issue, run the command `yum info file` in the build and non-build images and observe the difference in versions.

**Comment by mhart** [comment]
Here's what I get:
```
docker run --rm lambci/lambda:build-python3.6 yum info file
Loaded plugins: ovl
Installed Packages
Name        : file
Arch        : x86_64
Version     : 5.30
Release     : 11.34.amzn1
Size        : 84 k
Repo        : installed
From repo   : amzn-main
Summary     : A utility for determining file types
URL         : http://www.darwinsys.com/file/
License     : BSD
Description : The file command is used to identify a particular file according
            : to the type of data contained by the file.  File can identify many
            : different file types, including ELF binaries, system libraries,
            : RPM packages, and different graphics formats.
```

**Comment by mhart** [comment]
(maybe your `build-python3.6` image is out of date?)

**Comment by njv299** [comment]
Wow, you're right, I must have had a really stale version on my system....flushed all of my docker images, re-ran, and sure enough I get version 5.30.

Thanks for your help!

**Comment by mhart** [comment]
All good 👍
