### ISSUE TITLE
Document using AWS credentials inside non-build containers

### ISSUE THREAD

**Issue by smoll** [lambci/docker-lambda#171]
I tried following the recommendation to use env vars as described in https://github.com/lambci/docker-lambda/issues/4, however, it looks like due to the non-build images mirroring Lambda so closely, it now expects that the Lambda has authenticated using a https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html call.

I figured I would document my solution to save others the 6+ hours I spent on trial & error/researching it.

### 2) run this script

```bash
#!/usr/bin/env bash

cd "$(dirname "$0")/.."

# arbitrary name
json_file="assume-role-output.json"
# get this from AWS console > IAM
lambda_role="arn:aws:iam::1234567890:role/myfunction-dev-us-east-1-lambdaRole"
# passed to Docker via --env-file .env or env_file: in Docker Compose
env_file=".env"

aws sts assume-role \
  --role-arn "$lambda_role" \
  --role-session-name "DockerLambdaSession" > "$json_file"

AWS_DEFAULT_REGION="us-east-1"
AWS_ACCESS_KEY_ID=$(cat "$json_file" | jq --raw-output ".Credentials .AccessKeyId")
AWS_SECRET_ACCESS_KEY=$(cat "$json_file" | jq --raw-output ".Credentials .SecretAccessKey")
AWS_SESSION_TOKEN=$(cat "$json_file" | jq --raw-output ".Credentials .SessionToken")
EXPIRATION=$(cat "$json_file" | jq --raw-output ".Credentials .Expiration")

cat << EOF > $env_file
AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
EXPIRATION=$EXPIRATION
EOF
```

which will generate an .env file using the defaults from your credentials file:

```
AWS_DEFAULT_REGION=us-east-1
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxxx
AWS_SESSION_TOKEN=xxx
EXPIRATION=2019-03-09T20:15:46Z
```

note that you may have to periodically rerun this script, or set the expiration time to a longer one with `--duration-seconds` (default is 1 hour)

### 3) add your own username (those of the default credentials) as a Trusted Entity (IAM > nameOfLambdaRole > trusted relationships > Edit trusted relationship)

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::1234567890:user/yourusernamehere"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

### 4) enjoy access to AWS services from a non-build docker image!

**Comment by mhart** [comment]
@smoll can you explain a bit more in detail the issues you faced when just using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

There's nothing AFAIK in Lambda that requires STS/temporary credentials specifically.

**Comment by smoll** [comment]
@mhart this is extremely odd but I can no longer repro the issue I was seeing yesterday (`The AWS Access Key Id you provided does not exist in our records` cf. https://stackoverflow.com/questions/43907689/boto3-error-the-aws-access-key-id-you-provided-does-not-exist-in-our-records?rq=1) -- it maybe started happening due to my experiments using a multi-stage docker image build - due to having to build certain packages (e.g. opencv) in the build image and using `COPY --from` - and in the process also copying over a bad `boto3` dependency or something like that.

I'll go ahead and close this issue for now; will circle back if I figure out how to repro.
