### ISSUE TITLE
Setting lambda function memory size

### ISSUE THREAD

**Issue by Anjali05** [lambci/docker-lambda#175]
I am using the lambda docker image for local testing(Python 2.7). I want to know if there is any way I can set the function handler memory size in the argument list? Something like this, 
$ aws lambda update-function-configuration --function-name myfunction --memory-size 256

**Comment by mhart** [comment]
Docker allows you to restrict memory with the `-m` flag – and if you want to be 100% accurate you can also change the `AWS_LAMBDA_FUNCTION_MEMORY_SIZE` environment variable, so run it like this:

`docker run -m 1.5G -e AWS_LAMBDA_FUNCTION_MEMORY_SIZE=1536 ...`

**Comment by mhart** [comment]
Docker documentation is here: https://docs.docker.com/engine/reference/run/#user-memory-constraints

**Comment by Anjali05** [comment]
Is there any way of running lambda functions without docker? Like starting it directly inside the host.
