### ISSUE TITLE
OPENSSL_1.0.2 not found for python 3.6

### ISSUE THREAD

**Issue by killthrush** [lambci/docker-lambda#179]
Recently, I've been having trouble decoding JWTs using a lambda deployment constructed with LambCI `docker-lambda`.  Judging from the error trace below, it looks like a native dependency issue.  There were no errors *using* the container that I could see; nothing caused my build to fail.

```decoded = jwt_instance.decode(token, jwt.jwk_from_dict(k))
File "/var/task/backend/vendored/jwt/jwk.py", line 264, in jwk_from_dict
return supported[kty].from_dict(dct)
File "/var/task/backend/vendored/jwt/jwk.py", line 214, in from_dict
pub_numbers.public_key(backend=default_backend()), **dct)
File "/var/task/backend/vendored/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
_default_backend = MultiBackend(_available_backends())
File "/var/task/backend/vendored/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
"cryptography.backends"
File "/var/task/backend/vendored/cryptography/hazmat/backends/__init__.py", line 27, in <listcomp>
for ep in pkg_resources.iter_entry_points(
File "/var/task/backend/vendored/pkg_resources/__init__.py", line 2440, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/var/task/backend/vendored/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
from cryptography.hazmat.backends.openssl.backend import backend
File "/var/task/backend/vendored/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module>
from cryptography.hazmat.bindings._openssl import ffi as _ffi
ImportError: /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /var/task/backend/vendored/cryptography/hazmat/bindings/_openssl.abi3.so)```

I was using `jwt==0.5.2` when I got the error.  After updating to `jwt==0.6.1`, it looks like the error went away.  According to `pip freeze`, `jwt==0.5.2` depends on `cryptography==2.2.2`
and `jwt==0.6.1` on `cryptography==2.6.1`.  Is it possible that something broke here?  I can reproduce the issue reliably with the earlier version of the library.

Thanks!

**Comment by mhart** [comment]
Can you give some more details in how you're building your package, and how you're testing it on docker-lambda to ensure it runs ok?

OpenSSL 1.0.2 does not exist on Lambda (or the docker-lambda images), so the error is correct – I'm just not sure how you got it to succeed when running the container, unless you have a local copy of the openssl shared library that you haven't copied over with your package.

**Comment by mhart** [comment]
(the issue is that the cryptography hazmat prebuilt shared library, `_openssl.abi3.so`, depends on OpenSSL version 1.0.2 – if you can build your own `_openssl.abi3.so` that links to OpenSSL 1.0.1 instead, then it should work on Lambda)

**Comment by mhart** [comment]
Try `pip install cryptography --no-binary cryptography`

**Comment by killthrush** [comment]
Thanks!  Long story short, I'm returning to a particular serverless project that hasn't been touched in a number of months so it's possible something changed a long time ago and that something *used* to work.  I just wanted to make sure that this doesn't make it any further than my dev deployment =)

The build itself is very simple; just using a makefile to mount our code in the container and run pip:
```
$(VENDORED_FOLDER): requirements.txt    ## install requirements into $(VENDORED_FOLDER) when requirements.txt is newer than the folder
	rm -rf $(VENDORED_FOLDER)
	docker run -it -v $(shell pwd):/app lambci/lambda:build-python3.6 /bin/sh -c "pip install -r /app/requirements.txt -t /app/vendored/"
```

Our deps look like:
```
attrdict==2.0.0
boto3==1.5.20
botocore==1.8.34
deprecation==1.0
jwt==0.5.2
jsonschema==2.6.0
psycopg2==2.7.3.2
pyfaaster==0.1.12
pympler==0.5
requests==2.21.0
retrying==1.3.3
simplejson==3.11.1
toolz==0.9.0
voluptuous==0.11.5
```

From my perspective, the library upgrade is a perfectly suitable and even preferred solution.  I'll see if I can't get this older version working though.

**Comment by mhart** [comment]
I think the issue is more likely that `cryptography` have updated their requirements and now link to OpenSSL 1.0.2 whereas they didn't before.

As it says on the site, https://cryptography.io/en/latest/installation/ :

> Cryptography 2.4 has deprecated support for OpenSSL 1.0.1

**Comment by killthrush** [comment]
👍 Cool, yeah looks like using the following as my build command `pip install cryptography --no-binary cryptography && pip install -r /app/requirements.txt -t /app/vendored/` allowed me to use `jwt==0.5.2`.  We hadn't pinned `cryptography` so I think your theory on how this may have changed sounds legit.  Thanks for the assist!  I'll close this issue since I'm not longer seeing a problem on AWS.
