### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by jtoehen** [lambci/docker-lambda#180]
Did any of you hit this error lately? The last time it was successfully executed was in December 2018. I am running on Windows 10 with both WSL and Babun.

**Comment by mhart** [comment]
Can you give a little more detail?

**Comment by jtoehen** [comment]
Thanks for the quick response Michael. I try to recreate the issue in the following manner. You need serverless application model cli(sam cli) for it. Take note that App.class is there and this is built using openjdk 1.8. 

1. sam init --runtine java8
2. cd into the new app and maven build.
3. cp the newly built jar to a work directory.
4. extract all the content there.

~/lambda/sam-app/HelloWorldFunction/target/work$ ls
META-INF  com  helloworld

5. run the docker image but the error is showing

~/lambda/sam-app/HelloWorldFunction/target/work$ docker run --rm -v "$PWD":/var/task lambci/lambda:java8 helloworld.App
START RequestId: f0e15e2e-de53-49d8-94a6-0ec0083c808c Version: $LATEST
java.lang.ClassNotFoundException: helloworld.App
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)

END RequestId: f0e15e2e-de53-49d8-94a6-0ec0083c808c
REPORT RequestId: f0e15e2e-de53-49d8-94a6-0ec0083c808c  Duration: 4.11 ms       Billed Duration: 100 ms Memory Size: 1536 MB                                                                                      Max Memory Used: 3 MB

Environment info:
~/lambda/sam-app/HelloWorldFunction/target/work$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

~/lambda/sam-app/HelloWorldFunction/target/work$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

~/lambda/sam-app/HelloWorldFunction/target/work$ sam --version
SAM CLI, version 0.15.0

~/lambda/sam-app/HelloWorldFunction/target/work$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

~/lambda/sam-app/HelloWorldFunction/target/work$ cat META-INF/MANIFEST.MF
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: jtoehen
Created-By: Apache Maven 3.5.0
Build-Jdk: 1.8.0_191

**Comment by mhart** [comment]
I can't reproduce this – it works fine for me:

```console
$ sam init --runtime java8
$ cd sam-app
$ sam build
$ cd .aws-sam/build/HelloWorldFunction
$ docker run --rm -v "$PWD":/var/task lambci/lambda:java8 helloworld.App
START RequestId: 5fc9575b-5376-44e9-9238-21391c2d67f3 Version: $LATEST
END RequestId: 5fc9575b-5376-44e9-9238-21391c2d67f3
REPORT RequestId: 5fc9575b-5376-44e9-9238-21391c2d67f3	Duration: 2179.89 ms	Billed Duration: 2200 ms	Memory Size: 1536 MB	Max Memory Used: 32 MB	

{"body":"{ \"message\": \"hello world\", \"location\": \"74.66.0.148\" }","headers":{"X-Custom-Header":"application/json","Content-Type":"application/json"},"statusCode":200}
```

Maybe it's something to do with your environment (Windows specific?)

**Comment by jtoehen** [comment]
Thanks Michael.

**Comment by jtoehen** [comment]
It's indeed due to Docker for Windows. The latest run on WSL2 is working fine.
