### ISSUE TITLE
New images based on Amazon Linux 2

### ISSUE THREAD

**Issue by repinel** [lambci/docker-lambda#184]
Given https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/, are there any plans to release the languages' (except Node.js 10.x) images using Amazon Linux 2 as base?

**Comment by mhart** [comment]
No – none of the other runtimes use Amazon Linux 2 as a base

**Comment by mhart** [comment]
Note that the announcement you've linked to is about the base updating to Amazon Linux 1 version 2018.03 – not Amazon Linux 2.

The base of all docker-lambda image runtimes has already been updated for this: https://github.com/lambci/docker-lambda/commit/e2c23e6d10f6ff423611650cf235340f4d1f9adf

**Comment by repinel** [comment]
@mhart you are right! Thanks for the awesome project!
