### ISSUE TITLE
Check linux version

### ISSUE THREAD

**Issue by shlomi-viz** [lambci/docker-lambda#188]
I saw that you implemented changes to support the latest changes from AWS (https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/). How do I test on which version I'm running ( 2018.03 or older)? is there a flag that I need to use to run with the latest change?

Thanks.

**Comment by mhart** [comment]
On docker-lambda? All images are running on the latest version

**Comment by shlomi-viz** [comment]
Any way to confirm it? command that I can use to print the version name? I'm asking because it didn't looked like it's downloading a new image once I run the docker today. Thanks again.

**Comment by mhart** [comment]
All images were updated 7 days ago: https://hub.docker.com/r/lambci/lambda/tags
