### ISSUE TITLE
openssl version doesn't match live aws 

### ISSUE THREAD

**Issue by drzhouq** [lambci/docker-lambda#189]
The version on AWS Lambda is  "OpenSSL 1.0.1k-fips 8 Jan 2015". with following function:
```
import subprocess
def lambda_handler(event, context=None):
    logger.debug(subprocess.check_output(['openssl', 'version']).decode("utf-8"))
```
The version in  lambci/lambda:python3.6  is "OpenSSL 1.0.2k-fips 26 Jan 2017" (via command ```docker run --rm --entrypoint openssl lambci/lambda:python3.6 version```)

**Comment by mhart** [comment]
I get:

```
OpenSSL 1.0.2k-fips  26 Jan 2017
```

I think you must still be running on the old system – this would have updated on your code already, but the timeline for the update recently got extended by AWS:

https://aws.amazon.com/blogs/compute/updated-timeframe-for-the-upcoming-aws-lambda-and-aws-lambdaedge-execution-environment-update/

All the images here are running the latest versions.

You can add the layer `arn:aws:lambda:::awslayer:AmazonLinux1803` to update to the new version on your Lambdas

**Comment by drzhouq** [comment]
Thanks @mhart  you must have tried the AWS Lambda 3.7. I was reporting lambda 3.6. I tried quite a few regions (us-east-1, us-west-1 and eu-central-1) and all get "OpenSSL 1.0.1k-fips 8 Jan 2015".

**Comment by mhart** [comment]
Nope, I'm definitely on `python3.6`

<img width="783" alt="Screen Shot 2019-05-30 at 10 46 04 am" src="https://user-images.githubusercontent.com/367936/58640945-2ce84380-82c8-11e9-90f1-c008bb9e0940.png">

Again, I think you're probably not running your Lambdas with the latest changes.

Please confirm you have the `arn:aws:lambda:::awslayer:AmazonLinux1803` layer attached to your live Lambda.

**Comment by drzhouq** [comment]
you are right. Adding arn:aws:lambda:::awslayer:AmazonLinux1803 layer fixes this issue. Many thanks for let me know the existence of this layer. I would not be able to find it out by myself. I understand this is just a temporary workaround and it uses 1 of the 5 layers quota.

**Comment by mhart** [comment]
No probs – it was mentioned in the initial upgrade announcement, but you might have missed that:

https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

**Comment by Pechi77** [comment]
@mhart  I added this layer, but still my SSL version shows `OpenSSL 1.0.1e-fips 11 Feb 2013` and my script is not working, 
can you help.
![image](https://user-images.githubusercontent.com/16059874/79297239-376cf500-7efb-11ea-966d-6ec612007e26.png)

**Comment by mhart** [comment]
@Pechi77 you added which layer?

**Comment by Pechi77** [comment]
Hi @mhart I added this `arn:aws:lambda:::awslayer:AmazonLinux1803` for my lambda function

**Comment by mhart** [comment]
@Pechi77 Oh, you don't need to do that anymore – all environments got updated by July 29, 2019 as stated in the referenced posts.

How are you determining your SSL version? You should make sure you don't have any other layers that could be adding an older version of SSL (eg, what does the `cloudflarescrapingpackages` layer have in it?)

**Comment by Pechi77** [comment]
actually, I am using [couldscraper](https://pypi.org/project/cloudscraper/), works fine in locally, and not in lambda. I see SSL version in lambda by doing `import ssl; ssl.OPENSSL_VERSION` 
and it prints `1.0.1e-fips 11 Feb 2013`

**Comment by mhart** [comment]
Do you see the same thing if you run the command as shown here?

https://github.com/lambci/docker-lambda/issues/189#issue-449357998

**Comment by Pechi77** [comment]
Yes, I get the same output `OpenSSL 1.0.2k-fips  26 Jan 2017`

**Comment by mhart** [comment]
Er, that's a different output. That shows that the SSL version installed on Lambda is correct.

I think it's just the Python version that's showing an older version

**Comment by Pechi77** [comment]
Any help to make my script work in AWS Lambda?

**Comment by serivas** [comment]
I have a similar issue. Lambda has an old OpenSSL version installed. Getting this error:

DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
