### ISSUE TITLE
Unable to import module 'my_module': No module named 'my_module'

### ISSUE THREAD

**Issue by alexanderluiscampino** [lambci/docker-lambda#190]
Hi,

I am trying just to get the example to work:

# Test on Python 3.6 with a custom file named my_module.py containing a my_handler function
docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 my_module.my_handle

My setup is Windows10. Tried to use GIT Bash, PowerShell, but always get the same error.

Unable to import module 'my_module': No module named 'my_module'
{"errorMessage": "Unable to import module 'my_module'"}

This is telling me I can run the docker container fine, but somehow it is not finding my lambda my_module.py file.

I am using the following command:
PS C:\Users\user\Desktop\AWS_Layers\pandas> docker run --rm -v ${pwd}:/var/task lambci/lambda:python3.6 my_module.my_handler

My py file is in:
"C:\Users\user\Desktop\AWS_Layers\pandas\my_module.py"

My CWD/PWD:
C:\Users\user\Desktop\AWS_Layers\pandas

From other threads, this might have something to do with permissions, but did not see the solution posted to allow the permissions to the folder within the container. I am fairly beginner in this.

Thank you,

**Comment by mhart** [comment]
The Powershell env var is `${PWD}` isn't it? Or do caps not matter?

In any case, if that's not the issue, I can only think that this is a Docker setup issue of some sort. Can you mount a volume with any other image?

Eg, try running:

```
docker run --rm -v ${PWD}:/opt alpine ls -l /opt
```

**Comment by alexanderluiscampino** [comment]
Okay, running your code @mhart , I get an output of _total 0_

Is that the suppose outcome?

I also changed to run in a [ubuntu bash on windows 10](https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4) to completely replicate the correct bash env, and I keep getting the same error. The module.py is not found
<img width="767" alt="bash lambci" src="https://user-images.githubusercontent.com/32500355/58588187-f0f3a680-8213-11e9-8b88-24f8097e9964.PNG">

**Comment by mhart** [comment]
That's not the correct outcome, no – you should see a listing of the current directory.

I think your Docker setup isn't correct – it's not able to mount any local directory from the looks of it.

I'd try with just basic images (eg, `alpine`) and just try to get bind mounts working – this isn't an issue with `docker-lambda`. Documentation is here: https://docs.docker.com/storage/bind-mounts/

**Comment by mhart** [comment]
The main thing I'd check is whether Docker has access to the directories you're trying to run it from. `/mnt/c` looks to me like it might be a Windows volume, not a volume on Ubuntu?

**Comment by alexanderluiscampino** [comment]
How can I check if docker has access to this directory? It is a windows volume indeed, ubuntu is just the bash shell. But I get the same error either I run it in Git Bash/PowerShell/Ubuntu Bash

Should I also reinstall docker to make sure the setup is proper, in case is the mount problem?

**Comment by mhart** [comment]
I'm not sure what you mean by "Ubuntu is just the bash shell"? Aren't you running a full Ubuntu OS in a VM?

If so, try the following:

```
cd ~
touch somefile.txt
docker run --rm -v "$PWD":/opt alpine ls -l /opt
```

And you should at least see `somefile.txt` in the output. (I'm assuming the home directory on the VM isn't on `/c/mnt` – if it is, then you might have to try cd'ing into another directory, like `/tmp`)

If that still doesn't work, then I'm afraid I'm not sure what's up with your Docker setup – might be best to ask on StackOverflow or similar.

**Comment by alexanderluiscampino** [comment]
Indeed, the command above did not work, i did not see the "somefile.txt" listed.

But this command works:
`docker run --rm -v c:/Users:/data alpine ls /data`
returns my username

I am not running ubuntu on a VM. I'm running Windows Subsystem for Linux (WSL).

**Comment by mhart** [comment]
Ah, ok, then this should also work right?

```
docker run --rm -v c:/Users/user/Desktop/AWS_Layers/pandas:/data alpine ls /data
```

Then try:

```
docker run --rm -v c:/Users/user/Desktop/AWS_Layers/pandas:/var/task lambci/lambda:python3.6 my_module.my_handler
```

**Comment by mhart** [comment]
(if there are space in any of your paths then you'll need to escape them or use quotes)

**Comment by alexanderluiscampino** [comment]
`docker run --rm -v c:/Users/user/Desktop/AWS_Layers/pandas:/data alpine ls /data`
output: test

`docker run --rm -v c:/Users/user/Desktop/AWS_Layers/pandas:/var/task lambci/lambda:python3.6 my_module.my_handler`

output: Unable to import module 'my_module': No module named 'my_module'

**Comment by mhart** [comment]
What? Your first command says `test` is the only thing in that directory

**Comment by mhart** [comment]
You said in your issue description:

> My py file is in:
> "C:\Users\user\Desktop\AWS_Layers\pandas\my_module.py"

**Comment by alexanderluiscampino** [comment]
Not, that is only one of the folders in my pandas dir. Have more as image below

![image](https://user-images.githubusercontent.com/32500355/58594092-98c3a100-8221-11e9-842a-bdf77f7ab037.png)

**Comment by alexanderluiscampino** [comment]
![image](https://user-images.githubusercontent.com/32500355/58594166-c6104f00-8221-11e9-8466-0b75a9e8b0a9.png)

I have more stuff in that folder, see image above

**Comment by mhart** [comment]
But the only thing Docker can see is `test`?

**Comment by alexanderluiscampino** [comment]
apparently, that is what is happening. which is really strange and can't figure out why

**Comment by mhart** [comment]
Then it's probably a permissions issue like all the other issues you were referencing.

What does just doing this show?

```
ls -la c:/Users/user/Desktop/AWS_Layers/pandas
```

**Comment by mhart** [comment]
(not running in Docker – just in bash)

**Comment by alexanderluiscampino** [comment]
`ls: cannot access 'c:/Users/user/Desktop/AWS_Layers/pandas': No such file or directory`

**Comment by alexanderluiscampino** [comment]
indeed, permission issue, but how? I did not do anything special about any of these folders, literally just created them

**Comment by mhart** [comment]
I dunno – Windows is really not my forte, especially Docker on Windows. Might need to Google around, ask on StackOverflow, etc.

This issue popped up in a quick search, but you might find others more relevant:

https://github.com/docker/for-win/issues/969

When you figure it out, let us know 👍

**Comment by alexanderluiscampino** [comment]
@mhart  Thank you for your tireless help, I learned a lot about Docker in the process. Eventually, the answer was simpler:

It was due to the Windows Credentials, they needed to be updated. In the Docker App,
Settings -> Shared Drives -> Reset Credentials

Run as Administrator just to make sure.

**Comment by mhart** [comment]
Thanks for the update! Glad it worked out ok for you 👍
