### ISSUE TITLE
release version mismatch between :build-provided and :provided

### ISSUE THREAD

**Issue by nickbreen** [lambci/docker-lambda#192]
There is a mismatch between the release versions between the `build-provided` and `provided` tags.

This is due to release version differing in each: `build-provided` is `latest` (which ends up being `2018.03`) while `provided` is `2017.03`, where one would expect them to match!

Possible work arounds:

1. build using the runtime container? Though this is the old `2017.03` environment and new builds would be better using `2018.03`.
2. run using the build container? Makes it impractical to ensure that all libraries are available at the right version.

Possible solutions:

1. publish tags for `build-provided-2017.03`, `build-provided-2018.03` and `provided-2017.03`, `provided-2018.03` so that they can be explicitly tested. Generate these using the `arn:aws:lambda:::awslayer:AmazonLinux1803` and `arn:aws:lambda:::awslayer:AmazonLinux1703` layers.

----

My exact issue is linking against different openssl versions: 1.0.2k vs 1.0.1k.

Copying `libssl.so.1.0.2k` to `/opt/lib` would work if that path was earlier in lambda's LD_LIBRARY_PATH, but alas is it at the end.

----

```
$ docker build <<EOF
FROM lambci/lambda:build-provided
RUN yum -C repolist
RUN find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f
EOF
```
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM lambci/lambda:build-provided as build
 ---> 49b76ef13c9e
Step 2/3 : RUN yum -C repolist
 ---> Running in e2af0bf44123
Loaded plugins: ovl, priorities
repo id                               repo name                           status
amzn-main/latest                      amzn-main-Base                      0
amzn-updates/latest                   amzn-updates-Base                   0
repolist: 0
Removing intermediate container e2af0bf44123
 ---> 89b65f082102
Step 3/3 : RUN find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f
 ---> Running in a9c5417ed966
/usr/lib64/libssl.so.1.0.2k
find: `/var/runtime/lib': No such file or directory
find: `/var/task/lib': No such file or directory
find: `/opt/lib': No such file or directory
The command '/bin/sh -c find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f' returned a non-zero code: 1
```

```
$ docker build <<EOF
FROM lambci/lambda:provided
RUN yum -C repolist
RUN find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f
EOF
```
```
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM lambci/lambda:provided
 ---> 8b7c9c233f6c
Step 2/3 : RUN yum -C repolist
 ---> Running in 35db0574932b
repo id                               repo name                           status
amzn-main/2017.03                     amzn-main-Base                      0
amzn-updates/2017.03                  amzn-updates-Base                   0
repolist: 0
Removing intermediate container 35db0574932b
 ---> 0c3c84d6c363
Step 3/3 : RUN find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f
 ---> Running in aa323b0885b4
/usr/lib64/libssl.so.1.0.1k
find: `/var/runtime/lib': No such file or directory
find: `/var/task/lib': No such file or directory
find: `/opt/lib': No such file or directory
The command '/bin/sh -c find $(echo ${LD_LIBRARY_PATH} | tr : ' ') -name libssl.so\* -type f' returned a non-zero code: 1
```

**Comment by nickbreen** [comment]
Duplicates #191

**Comment by mhart** [comment]
Yeah, `lambci/lambda:provided` was updated at the same time as `lambci/lambda:build-provided` a few weeks ago – it may just be that you had updated one and not the other

**Comment by nickbreen** [comment]
Yes, that was exactly the issue. 

I was also using `sam local` with `--skip-pull-image` to speed up builds, which if I hand't would have avoided the issue too.
