### ISSUE TITLE
Does Lambci docker image always execute handler when it boots up (even without event feed)?

### ISSUE THREAD

**Issue by cosmir17** [lambci/docker-lambda#195]
I have two quetions. 
The following docker file(extending your docker Lambda image) runs and invokes my handler but without event feed. Therefore, my handler throws null pointer exception.
1) Is it normal?
2) If there is a way to boot up a container without event feed, I want to send a message to this docker container so that I can send a query from Cucumber(Gherkin) test cases. http or websocket or any other means are fine. Any suggestions?

<img width="590" alt="Screenshot 2019-06-15 at 07 24 53" src="https://user-images.githubusercontent.com/2845708/59556252-63f07180-8fb7-11e9-8a73-d2e97c07e99f.png">

**Comment by justjacksonn** [comment]
I would like to know too. I want to run it in a daemon/server sort of mode so my function runs locally and responds to requests continually, then send requests from a local app. This way I can modify my function locally and quickly restart the docker container with it, and/or can work on the client side app that is making the call to the function. Would really like to know how to do this.

**Comment by mhart** [comment]
docker-lambda now supports a "stay-open" mode where you can continually query it: https://github.com/lambci/docker-lambda/#running-in-stay-open-api-mode
