### ISSUE TITLE
Running sam local invoke within lambci/lambda:build-python3.7

### ISSUE THREAD

**Issue by hevy-CC4477** [lambci/docker-lambda#197]
I am trying to run sam local invoke with in lambci/lambda:build-python3.7 without success. Docker seems to be installed or accessible at least, but is not running within this container. Is there some settings to provide ?

```
> sam local generate-event s3 put --bucket somebucket --key SOMEKEY | sam local invoke
2019-07-02 23:32:35 Reading invoke payload from stdin (you can also pass it from file with --event)
Error: Running AWS SAM projects locally requires Docker. Have you got it installed?
> docker --version
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
```

**Comment by mhart** [comment]
This seems to be a SAM CLI issue and unrelated to this repo. If you have problems using docker directly feel free to reopen

**Comment by hevy-CC4477** [comment]
Sorry I wanted to give an example. here is one more generic:
```
docker run -it lambci/lambda:build-python3.7 bash
bash-4.2# docker --version
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
bash-4.2# docker pull lambci/lambda:python3.7
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
What should I do to be able to docker inside my container ?

**Comment by mhart** [comment]
Sorry, you're trying to run docker from within docker?

**Comment by hevy-CC4477** [comment]
Yes !

**Comment by mhart** [comment]
Well that's really a docker question, nothing to do with this repo – see similar questions here: https://forums.docker.com/t/how-can-i-run-docker-command-inside-a-docker-container/337

But the usual way to do it would be like this:
```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock lambci/lambda:build-python3.7 bash
```

**Comment by hevy-CC4477** [comment]
Ok, I did not know. Thanks for the answer, it works!
