### ISSUE TITLE
build-nodejs10.x, sam, has RequestsDependencyWarning urllib3 chardet doesn't match a supported version

### ISSUE THREAD

**Issue by diablodale** [lambci/docker-lambda#198]
### Setup

* Ubuntu 18.04.2 LTS on amd64
* Docker CE version 18.09.7

### Repo

1. `docker pull lambci/lambda:build-nodejs10.x`
2. `docker run -ti lambci/lambda:build-nodejs10.x bash`
3. `sam`

### Result

```
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Usage: sam [OPTIONS] COMMAND [ARGS]...

  AWS Serverless Application Model (SAM) CLI
...
```

### Expected

No python RequestsDependencyWarning

**Comment by mhart** [comment]
This has been fixed at some point by SAM upstream
