### ISSUE TITLE
Example for compiling PhantomJS

### ISSUE THREAD

**Issue by adelevie** [lambci/docker-lambda#2]
This project is awesome and could not have come at a better time.

> You can also use it to compile native dependencies knowing that you're linking to the same library versions that exist on AWS Lambda and then deploy using the AWS CLI.

I'd love to replace https://github.com/18F/pa11y-lambda/blob/eecdd5d283de34e437847e21eed9314f27001aba/app/phantomjs_install.js with a pre-built PhantomJS binary that I know will Just Work in the Lambda environment.

According the the [PhantomJS docs](http://phantomjs.org/build.html), you build it by obtaining the source and then running `python build.py`. I'm new to both PhantomJS building and Docker, so I was wondering if you could give a rough idea of how that workflow could fit in this Docker toolchain.

**Comment by mhart** [comment]
Actually, phantomjs should just work outta the box on Lambda – at least, it has in all the examples I've tried. Use `npm install phantomjs-prebuilt`

**Comment by mhart** [comment]
Sorry, more docs here: https://github.com/Medium/phantomjs

**Comment by adelevie** [comment]
I recall some bad experiences using that in Lambda. I'll close this issue, follow up at some point, and re-open if PhantomJS doesn't just work using `phantomjs-prebuilt`. Thanks!

**Comment by mhart** [comment]
No probs, good luck! It may be that recent phantom changes have made it easier? Or maybe I just got lucky! I certainly remember the https://github.com/ariya/phantomjs/blob/master/examples/phantomwebintro.js example working – which made me think that covered a lot of bases... but maybe not enough?
