### ISSUE TITLE
Failed to load resource after build lambci/lambda:nodejs8.10

### ISSUE THREAD

**Issue by Minor946** [lambci/docker-lambda#201]
```
sam --version
SAM CLI, version 0.18.0

```
```
docker --version
Docker version 18.09.2, build 6247962
```

After start on **sam local start-api** and **lambci/lambda:nodejs8.10** Docker container image
and open localhost:3000, all assets files return **Failed to load resource: the server responded with a status of 403 (FORBIDDEN)**
```
2019-07-26 17:20:35 127.0.0.1 - - [26/Jul/2019 17:20:35] "GET /public/lib/button.css HTTP/1.1" 403 -
2019-07-26 17:20:35 127.0.0.1 - - [26/Jul/2019 17:20:35] "GET /public/lib/menu.css HTTP/1.1" 403 -
```

PS. Shared drives in docke **turn on**

**Comment by mhart** [comment]
I don't think this is a docker-lambda bug – have you opened an issue at SAM CLI or asked on the Slack?

**Comment by Minor946** [comment]
ok ,i'll try, thx
