### ISSUE TITLE
Upgrading `GCC` for python3.7

### ISSUE THREAD

**Issue by marcmetz** [lambci/docker-lambda#204]
First of all, these docker images solved lot's my problems I was dealing with, thank you. I have one last problem. Trying to install the pip package `fbprophet` I am running into an error. I now figured out the issue which is related to `pystan`. In their [newest version](https://pystan.readthedocs.io/en/latest/whats_new.html) it says:

> Stan 2.19 requires a compiler which supports C++14. For example, if you use gcc as your compiler you will need to use gcc version 4.9.3 or higher.

It seems like, these images here use an older gcc version? Is it planned in the future to upgrade these?

**Comment by mhart** [comment]
We install the version of gcc available for the base OS that Lambda is running on using `yum`. (ie, essentially, `yum install gcc`)

For Amazon Linux 1 based Lambdas, that's gcc 4.8.5. For Amazon Linux 2 based Lambdas (currently only `nodejs10.x`) it's gcc 7.3.1. This ensures that software built with those versions will also be linked correctly with the libgcc/libstdc++ versions installed on Lambda.

You can try installing a newer version of gcc on your build image and seeing if that works for you – but there's also a chance that you'll need to distribute a newer version of libgcc and/or libstdc++ if Stan links to that as well.

Eg, try:

```
docker run --rm lambci/lambda:build-python3.7 bash
> yum install -y gcc72    # or gcc64
> pip install ...
```
