### ISSUE TITLE
lambci/lambda:nodejs10.x console log mangled output

### ISSUE THREAD

**Issue by antoniuslin** [lambci/docker-lambda#209]
Hello,

I hope this is the right place to raise this topic.
I've recently moved to use `lambci/lambda:nodejs10.x` docker image from `lambci/lambda:nodejs8.10` for SAM local development. I encountered a situation where large object `console.log` output from the `10.x` image is mangled, in comparison to the output from `8.10` image.

Example of a lambda output from `10.x`, below:

```
2019-09-05T19:58:21.673Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	--- pg test begins
2019-09-05T19:58:21.674Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	my db area: local
2019-09-05T19:58:21.676Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	database psb
  rowAsArray: false }[Object] },: setTypeParser],'ProcessLogs' } ],2	INFO	queryResult: Result {
2019-09-05T19:58:21.697Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	--- pg test ends
```

Example of the same lambda output from `8.10`, below:

```
2019-09-05T19:59:07.405Z	2bbbc994-631c-109e-70b9-0f2d861a8d1d	--- pg test begins
2019-09-05T19:59:07.406Z	2bbbc994-631c-109e-70b9-0f2d861a8d1d	my db area: local
2019-09-05T19:59:07.407Z	2bbbc994-631c-109e-70b9-0f2d861a8d1d	database psb
2019-09-05T19:59:07.424Z	2bbbc994-631c-109e-70b9-0f2d861a8d1d	queryResult: Result {
  command: 'SELECT',
  rowCount: 2,
  oid: null,
  rows: [ { Table: 'knex_migrations' }, { Table: 'ProcessLogs' } ],
  fields:
   [ Field {
       name: 'Table',
       tableID: 12948,
       columnID: 3,
       dataTypeID: 1043,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function: noParse] ],
  _types:
   TypeOverrides {
     _types:
      { getTypeParser: [Function: getTypeParser],
        setTypeParser: [Function: setTypeParser],
        arrayParser: [Object] },
     text: {},
     binary: {} },
  RowCtor: null,
  rowAsArray: false }
2019-09-05T19:59:07.427Z	2bbbc994-631c-109e-70b9-0f2d861a8d1d	--- pg test ends
```

The code is a simple `console.log` call, eg., `console.log('queryResult:', queryResultObject);`.

**Comment by mhart** [comment]
This is unfortunately due to how the nodejs10.x runtime messes with `console.log` (on production Lambda). It replaces all newlines with `\r` (as well as adding the `INFO` column). `docker-lambda` doesn't modify any of this behavior (deliberately)

You might be able to run the output through `tr '\r' '\n'`?

**Comment by antoniuslin** [comment]
That is indeed unfortunate. I don't mind at all running the output through `tr` command, although I feel like in this case, it really should've been kept as a `\n` rather than a `\r` since I really don't like to override a built-in object. Would you say there's another place I may be able to raise this same topic for the nodejs10.x runtime team to re-consider this newline to carriage return replacement thing?

Thanks much again.

**Comment by mhart** [comment]
There is a way to override this behavior – I'm not sure if it's documented yet. Lambda uses an AWS node module (which I don't think is published) to transform the console.

Try this to get the old behavior:

```js
const { logger, appenders, layouts } = require('lambda-logging')
logger.appender = new appenders.ConsoleAppender(new layouts.Node4LegacyLayout())

// Do that ^ before your handler
exports.handler = async(event, context) => {
  // ...
}
```

**Comment by antoniuslin** [comment]
Thanks for the follow-up.
The prepended code block seems to be ineffective as the produced output is still the same as the output produced without it.

**Comment by mhart** [comment]
Ugh, you're 100% correct. Even using that layout they replace newlines – it's not even backwards compatible 😠 

If you create your own `Layout` class like so, then you could use it:

```js
const { logger, appenders, transformers } = require('lambda-logging')

class NoCarriageReturnLayout {
  format(level, message, event) {
    const time = transformers.timestampTransformer.getFromEvent(event).toISOString()
    const requestId = transformers.requestTransformer.getFromEvent(event)
    return `${time}\t${requestId}\t${message}`
  }
}

logger.appender = new appenders.ConsoleAppender(new NoCarriageReturnLayout())

// Do that ^ before your handler
exports.handler = async(event, context) => {
  // ...
}
```

If you don't care about the timestamp or requestId for each log, then you could just do:

```js
const { logger, appenders } = require('lambda-logging')

class PassthroughLayout {
  format(level, message, event) {
    return `${message}`
  }
}

logger.appender = new appenders.ConsoleAppender(new PassthroughLayout())

// Do that ^ before your handler
exports.handler = async(event, context) => {
  // ...
}
```

**Comment by antoniuslin** [comment]
@mhart, thank you so much! This works. I added back the `INFO` output as I do not wish to change whatever is supposedly intended for the nodejs10.x lambda engine; simply wished the output corrected. So I took and used your first snippet (plus INFO).

```
2019-09-07T20:47:14.642Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	--- pg test begins
2019-09-07T20:47:14.642Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	my db area: local
2019-09-07T20:47:14.644Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	database psb
2019-09-07T20:47:14.663Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	queryResult: Result {
  command: 'SELECT',
  rowCount: 2,
  oid: null,
  rows: [ { Table: 'knex_migrations' }, { Table: 'ProcessLogs' } ],
  fields:
   [ Field {
       name: 'Table',
       tableID: 12948,
       columnID: 3,
       dataTypeID: 1043,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function: noParse] ],
  _types:
   TypeOverrides {
     _types:
      { getTypeParser: [Function: getTypeParser],
        setTypeParser: [Function: setTypeParser],
        arrayParser: [Object] },
     text: {},
     binary: {} },
  RowCtor: null,
  rowAsArray: false }
2019-09-07T20:47:14.664Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	--- pg test ends
```

Thanks again for attending to my questions.
Have great one!
