### ISSUE TITLE
Recycled RequestId

### ISSUE THREAD

**Issue by antoniuslin** [lambci/docker-lambda#210]
Hello,

When I ran my lambda using local SAM, I ran into some issues that I couldn't reproduce when the lambda is run on AWS, which upon further inspection I found that it's due to my reliance of the context request id itself. 

Having said that, I could simply change my logic to generate my own random request id, but it seems an unnecessary work which I would then need to tie back my request id to the actual lambda request id. Is there a way to correct the local SAM so that it produces unique request id with every lambda execution?

Thanks much.

Sample observed duplications below:

```
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
...
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 478.39 ms	Billed Duration: 500 ms	Memory Size: 128 MB	Max Memory Used: 59 MB
No Content-Type given. Defaulting to 'application/json'.
2019-09-20 16:15:10 10.0.2.2 - - [20/Sep/2019 16:15:10] "POST /mylambda?mode=debug HTTP/1.1" 200 -
Invoking app.makeDsr (nodejs10.x)
```

Note the same `RequestId` at different timestamp above @ `2019-09-20 16:15:10` and below @ `2019-09-20 16:26:13`

```
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
...
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 505.39 ms	Billed Duration: 600 ms	Memory Size: 128 MB	Max Memory Used: 60 MB
No Content-Type given. Defaulting to 'application/json'.
2019-09-20 16:26:13 10.0.2.2 - - [20/Sep/2019 16:26:13] "POST /mylambda?mode=debug HTTP/1.1" 200 -
```

**Comment by mhart** [comment]
Well spotted! This should be fixed for the nodejs10.x runtime now (it was already this way on nodejs8.10 and nodejs6.10)
