### ISSUE TITLE
Please create a dockerized version of graalvm

### ISSUE THREAD

**Issue by Ravisankar-Challa** [lambci/docker-lambda#213]
Graal VM lets us compile Java code to native code. To compile to native code we need a version of dockersied lambci. 
Reason for asking this is I compiled java code to native code using Graal VM in Ubuntu Linux and tried to run in AWS lamda it failed. Native code is not portable so it would be better to have a docker version of lambci with graal vm to compile to native code for AWS lambda.

Below are the list of commands to be executed to create docker image.
yum install -y gcc zlib-devel curl

export GRAAL_VERSION=19.2.0.1
export GRAAL_FILENAME=graalvm-ce-linux-amd64-${GRAAL_VERSION}.tar.gz

curl -4 -L https://github.com/oracle/graal/releases/download/vm-${GRAAL_VERSION}/${GRAAL_FILENAME} -o /tmp/${GRAAL_FILENAME}

tar -zxvf /tmp/${GRAAL_FILENAME} -C /opt
cd /opt/graalvm-ce-${GRAAL_VERSION}/bin
gu install native-image

rm -rf /tmp/${GRAAL_FILENAME}

**Comment by mhart** [comment]
Thanks for the instructions @Ravisankar-Challa! I'm sure many ppl will find this useful if they want to compile Graal VM programs that run on Lambda.

I'm not going to create and maintain a separate image in this repository for Graal VM – the images in this repository are specifically for the supported runtimes in AWS Lambda.

But it's good to know you can just add the above commands to your own build process 👍
