### ISSUE TITLE
Stop Using Python 2.7

### ISSUE THREAD

**Issue by metaskills** [lambci/docker-lambda#215]
I've noticed the `build-` variants (maybe more) use Python 2.7 and output the following error.

> Warning : AWS SAM CLI will no longer support installations on 
> Python 2.7 starting on October 1st, 2019. Install AWS SAM CLI via 
> https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html 
> for continued support with new versions.

```shell
$ docker run --interactive --tty lambci/lambda:build-ruby2.5 bash
> bash-4.2# sam --version
Warning : AWS SAM CLI will no longer support installations on Python 2.7 starting on October 1st, 2019. Install AWS SAM CLI via https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html for continued support with new versions.
```

I've not had issues with 2.7 yet, I think. However I did want to ask if dropping 2.7 was on the next release roadmap?

**Comment by mhart** [comment]
Yeah, this is a good point – I do want to switch to using python 3.x, but I was a bit concerned about breaking anyone's existing workflows. I guess I'll just have to bite the bullet and do it 👍

**Comment by mhart** [comment]
Done as of bc38b5aa871b72a159c75ffbe3a194db4a67e9e2

**Comment by metaskills** [comment]
Thanks for your work on this! Great knowledge drops on on Serverless Chats too. Cheers!
