### ISSUE TITLE
dotnetcore2.1 container printing NULLs after result

### ISSUE THREAD

**Issue by sanathkr** [lambci/docker-lambda#219]
We had someone report this issue in SAM CLI today - https://github.com/awslabs/aws-sam-cli/issues/1517. I haven't gotten a chance to repro the issue yet.

Going through the code, I see you had made changes to the dotnetcore mock runner, specifically this line: https://github.com/lambci/docker-lambda/blob/master/dotnetcore2.1/run/MockBootstraps/MockRuntime.cs#L121

I see how it would print a bunch of NULL if you were serializing the entire buffer without stopping at the null byte.

Do you think this is a regression?

**Comment by mhart** [comment]
Should have been fixed a couple of days ago: https://github.com/lambci/docker-lambda/commit/c833c00477c1b1a59881fbe32f87287981a21062

**Comment by mhart** [comment]
(looks like they reported it a couple of days ago – so that probably lines up. There was a small window of an hour or so where this bug could have been triggered)
