### ISSUE TITLE
sam local invoke timeout with nodejs8.10

### ISSUE THREAD

**Issue by mariano-calandra-xp** [lambci/docker-lambda#223]
I have a Lambda developed with NodeJS 8.10. Until few hours ago I could execute this command:

`sam local invoke -e test/create-order.fn.json -n test/create-order.integration.env.json CreateOrderFunction`

and obtain the return value of the function. Right now, without touching the code, that Lambda go timeout:

> 2019-11-19 23:59:30 Found credentials in shared credentials file: ~/.aws/credentials
> 2019-11-19 23:59:30 Invoking src/create-order-lambda.handler (nodejs8.10)
> 
> Fetching lambci/lambda:nodejs8.10 Docker container image......
> 2019-11-19 23:59:34 Mounting /Users/mariano/Repositories/personal/wpc19/order as /var/task:ro,delegated inside runtime container
> START RequestId: 424ba675-1217-150d-c41f-62c9fc990d0d Version: $LATEST
> 2019-11-19 23:59:37 Function 'CreateOrderFunction' timed out after 3 seconds

Am I the only with this problem or something has changed in lambci?

PS: I update Docker in the morning, this could have broke something. Anyone in my situation?

**Comment by mhart** [comment]
You're the only one to report it (so far), but there have been a bunch of changes in the last few days to the lambci images. Let me see if I can reproduce.

**Comment by mhart** [comment]
Hmmm, it works fine for me with a basic lambda function. Is there something in particular you're doing in your function? Can you give me a handler file that can reproduce this?

**Comment by mhart** [comment]
Are you using the `aws-xray-sdk` module by any chance? There were some changes made recently to one of the X-Ray environment variables

**Comment by mariano-calandra-xp** [comment]
> Are you using the `aws-xray-sdk` module by any chance? There were some changes made recently to one of the X-Ray environment variables

Yep, I've found the topic related. Sorry for the loss of time :)

**Comment by mhart** [comment]
Sorry, can you explain what the problem was?
