### ISSUE TITLE
Connecting to DynamoDB

### ISSUE THREAD

**Issue by limianwang** [lambci/docker-lambda#23]
I was doing some prototyping with AWS Lambda, and successfully ran the code within the docker container. However, when I wanted to extend the lambda functionality to connect to another docker container for Dynamodb, it doesn't seem to work. 

This is what I've done:

```
docker run -d --name dynamodb deangiberson/aws-dynamodb-local
docker run --links dynamodb:dynamodb -v "$PWD":/var/task lambci/lambda index.handler
```

But when it attempts to connect, this is what it says:

```
{"errorMessage":"connect ECONNREFUSED 127.0.0.1:8000","errorType":"NetworkingError","stackTrace":["Object.exports._errnoException (util.js:870:11)","exports._exceptionWithHostPort (util.js:893:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)"]}
```

I'm running on Docker 1.13.1 (Docker for Mac)

Anyone else had this issue?

Thanks!

**Comment by justinmchase** [comment]
I also connect to dynamo from my local lambda and it works for me, so it is possible. I use docker-compose to setup links because its easier but from first glance based on what you have there you need to expose the port on your dynamodb container and you also need to create a network and have them both join it:

```
docker network create test
docker run -d --name dynamodb --network test -p 8000:8000 deangiberson/aws-dynamodb-local
docker run --links dynamodb:dynamodb --network test -v "$PWD":/var/task lambci/lambda index.handler
```

**Comment by njcongtou** [comment]
do you have resolution ?

**Comment by justinmchase** [comment]
The trick is to put them on the same network `--network test`

**Comment by njcongtou** [comment]
is your Lambda function in Node ? I am having this issue to access localstack s3 service. 



This is my hello world nodejs lambda.

environment:
  - SERVICES=${SERVICES-lambda, kinesis, s3}
  - DEBUG=1
  - DATA_DIR=${DATA_DIR- }
  - LAMBDA_EXECUTOR=docker
  - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  - DOCKER_HOST=unix:///var/run/docker.sock
  - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME- }
Reference LOCALSTACK_HOSTNAME in my code:

s3 = new AWS.S3({ apiVersion: '2006-03-01', endpoint: '${process.env.LOCALSTACK_HOSTNAME}:4572'});

Error:

localstack_1 | module initialization error: ReferenceError
localstack_1 | at Object. (/var/task/index.js:5:4)
localstack_1 | at Module._compile (module.js:570:32)
localstack_1 | at Object.Module._extensions..js (module.js:579:10)
localstack_1 | at Module.load (module.js:487:32)
localstack_1 | at tryModuleLoad (module.js:446:12)
localstack_1 | at Function.Module._load (module.js:438:3)
localstack_1 | at Module.require (module.js:497:17)
localstack_1 | at require (internal/module.js:20:19)

**Comment by DaveCollinsJr** [comment]
Thanks for this @justinmchase !!  Also FYI for anyone trying to link to another docker container that is running an API via docker-compose:
```
docker network
docker network <container-network-name> inspect
```
Then you can use the IP address exposed by that command to test, for example, your Lambda API client locally from a container run by the the commands in the docker-lambda Readme.

**Comment by nkravi** [comment]
Now with the new docker version use of --link is deprecated. Do you guys have any other approach for this?

**Comment by mhart** [comment]
AFAICT this isn't docker-lambda specific – general docker network settings should work here.
