### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by SamHashemiCA** [lambci/docker-lambda#230]
Hi All,

I'm trying to build a Lambda Function using PyCharm AWS Toolkit and I receive this error which I couldn't track down:
```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

**Comment by mhart** [comment]
How are you building it? By invoking `docker run lambci/lambda...` directly?

If not, this might be an issue you should post over at https://github.com/awslabs/aws-lambda-builders
