### ISSUE TITLE
SAM cli is not updated to newest version in build-dotnetcore2.1

### ISSUE THREAD

**Issue by mrlindgren** [lambci/docker-lambda#232]
The build-dotnetcore2.1 image is using: SAM CLI, version 0.22.0:
`docker run --rm -v "$PWD":/var/task lambci/lambda:build-dotnetcore2.1 sam --version`

Command for updating the cli version is located in dotnetcore2.1/build/Dockerfile but returns errors:
`docker run --rm -v "$PWD":/var/task lambci/lambda:build-dotnetcore2.1 pip install aws-sam-cli==0.34.0`:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting aws-sam-cli==0.34.0
  ERROR: Could not find a version that satisfies the requirement aws-sam-cli==0.34.0 (from versions: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.21.0, 0.22.0, 0.23.0)
ERROR: No matching distribution found for aws-sam-cli==0.34.0
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Other images are using the newest version: SAM CLI, version 0.34.0
`docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs10.x sam --version`

**Comment by mhart** [comment]
What is the digest sha of your build-dotnetcore2.1 image? I think you might be out of date and probably haven't pulled in quite a while.

**Comment by mrlindgren** [comment]
You were right - Thanks! Sorry for the inconvenience.
