### ISSUE TITLE
lambci/lambda:nodejs12.x does not have fontconfig package installed

### ISSUE THREAD

**Issue by KrishKayc** [lambci/docker-lambda#233]
Hi,

We are upgrading from node 8 to 12 in lambda.

Seems the image lambci/lambda:nodejs12 does not have fontconfig package in it. The same issue is with amazonlinux:2 image.

From code, we do spawn('fc-list') to get the list of fonts and it is throwing error because fc-list is not at all available (since package fontconfig isn't available)

This did not happen in lambci/lambda:nodejs8.10

Since we cannot do any yum installs in the actual lambda execution environment, we are not sure what to do with this.

**Comment by mhart** [comment]
That's right – AWS have stripped down the OS a lot since `nodejs10.x`

Check out https://github.com/lambci/yumda as a way to solve this – you can install fontconfig for your Lambda that way
