### ISSUE TITLE
Running a golang lambda in Docker with multi-stage builds

### ISSUE THREAD

**Issue by JPZ13** [lambci/docker-lambda#238]
Hello,

I'm trying to build a Docker image of a lambda handler in golang but keep running into the following error when I specify `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`: 

`An error occurred (UnrecognizedClientException) when calling the UpdateFunctionCode operation: The security token included in the request is invalid.`

When I don't set those variables, I get the following error:
`Unable to locate credentials. You can configure credentials by running "aws configure"`

Do the access key and secret need to conform to some set standard even if I'm running the lambda locally?

Here's my dockerfile:
```
FROM lambci/lambda:build-go1.x

ENV GO111MODULE=on
ENV AWS_DEFAULT_REGION us-east-1

WORKDIR /app

# cache go modules
COPY functions/dynamo-to-elasticsearch/go.mod .
COPY functions/dynamo-to-elasticsearch/go.sum .
COPY shared /shared

RUN go mod download

COPY functions/dynamo-to-elasticsearch .

RUN go build -o dynamo-to-elasticsearch
RUN zip -9yr lambda.zip dynamo-to-elasticsearch

CMD aws lambda update-function-code \
  --function-name dynamo-to-elasticsearch \
  --zip-file fileb://lambda.zip
```

Additionally, I've been using placeholders like `test-key-id` and `test-secret-key` when adding the environment variables.

**Comment by mhart** [comment]
You're running `aws lambda update-function-code` – that's going to update real function code in AWS production, which you'll need AWS credentials for

**Comment by JPZ13** [comment]
Thank you, @mhart. Is there a way to update a lambda running locally within a dockerfile without using a volume? I'm just going off the documentation [here](https://github.com/lambci/docker-lambda#using-a-dockerfile-to-build)

**Comment by mhart** [comment]
There are a couple of options here – one is to run docker-in-docker using the build image. ie, after you've built your binary, then execute `docker run lambci/lambda:go1.x ...` from within the build image. This is unusual though.

More usual would be to build the lambda first and get the built artifacts out, then run it separately using a a non-build image (ie `lambci/lambda:go1.x`).

So in your case, you just need to get your `dynamo-to-elasticsearch` binary out of the build docker image – either using volumes or `docker cp` or whichever method you prefer.

Once you've copied `dynamo-to-elasticsearch` to the current directory (or whichever directory you prefer), then you can run your lambda using `docker run -v "$PWD":/var/task lambci/lambda:go1.x`

**Comment by mhart** [comment]
Also, I should note, you don't need to write a Dockerfile and build a docker image to build your lambda. You could just mount a directory and execute the build commands in a `docker run lambci/lambda:build-go1.x` command. Depends on whether you want the caching, etc.

**Comment by JPZ13** [comment]
Thanks @mhart 

I need to include everything in an image so that my team can use the image in various CI/CD environments that may or may not have access to the actual code for running the volume. I came up with the following multi-stage build that seems to be working:

```
# build lambda zip
FROM lambci/lambda:build-go1.x AS builder

ENV GO111MODULE=on
ENV AWS_DEFAULT_REGION us-east-1

WORKDIR /app

# cache go modules
COPY functions/dynamo-to-elasticsearch/go.mod .
COPY functions/dynamo-to-elasticsearch/go.sum .
COPY shared /shared

RUN go mod download

COPY functions/dynamo-to-elasticsearch .

RUN go build -o dynamo-to-elasticsearch

FROM lambci/lambda:go1.x

# copy binary
COPY --from=builder /app/dynamo-to-elasticsearch dynamo-to-elasticsearch

ENTRYPOINT ["/var/runtime/aws-lambda-go", "./dynamo-to-elasticsearch"]
```

A gotcha that other people might run into is that the entrypoint needs to the lambda go runtime instead of just running the binary directly using `CMD ./dynamo-to-elasticsearch`. I'll re-title the issue so that others can find the above easier and close the issue.

Thank you for maintaining this project @mhart and for responding to issues

**Comment by mhart** [comment]
Nice - that's a good way to go. Another option would be:

```
FROM lambci/lambda:go1.x

# copy binary
COPY --from=builder /app/dynamo-to-elasticsearch dynamo-to-elasticsearch

ENV _HANDLER dynamo-to-elasticsearch
```

Then you don't need the (arguably more brittle) entrypoint customization. Depends on how you want to pass in the event though. Can either use the command line option (which I guess is what you're currently doing), or the `AWS_LAMBDA_EVENT_BODY` 
 env var, or set `DOCKER_LAMBDA_USE_STDIN=1` and then pipe stdin in (will need `docker run -i`)

**Comment by JPZ13** [comment]
You da man! I appreciate the tips
