### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by 6iix** [lambci/docker-lambda#248]
I am using WSL2 and arm64 architecture. Is there any plans or anyway to make this container available in that architecture? 

I would create a pull request, but I am not a docker expert.

**Comment by mhart** [comment]
Lambda runs on x86-64 so I'm not even sure how this would be possible?

**Comment by 6iix** [comment]
That is good point. I was just hoping to be able to use my new machine for lambda development. I was poking around the repo and I am wondering why not make it cross platform? Would it really create a big discrepancy  between local development and pushing to aws?

**Comment by mhart** [comment]
It probably would yeah – one of the main reasons for using docker containers for Lambda is to ensure that your software will run in the same way it does in the cloud. If you're using different architectures, then that falls apart. (you couldn't deploy any natively compiled binaries that were working locally for example)

Aside from that, it would be a huge task to try and recreate the Lambda environment for a completely different architecture – from installing all the same OS packages to trying to recreate all the (closed source) Lambda native libraries.

I think if you want to do this, then I'm assuming you don't have any native dependencies, so I'd just avoid using docker containers altogether.

**Comment by 6iix** [comment]
@mhart that makes sense. Thank you for the quick, clear concise response. It was a shot in the dark anyways. I'll close this issue.

**Comment by david-l-riley** [comment]
I should note that Docker images can run under QEMU, which may be supported on the Docker for Windows install (I know it is for Docker for Mac). That should make it possible to run the container if it's supported, though obviously the performance wouldn't be representative (probably good enough for many lambdas, but I wouldn't run benchmarks on it).

**Comment by swetankkk** [comment]
https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by kunickiaj** [comment]
> Lambda runs on x86-64 so I'm not even sure how this would be possible?

Lambda is available on arm64 Graviton now and it costs 35% less than on Intel. Would love to see this issue reopened.
ref: https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by monim67** [comment]
> Lambda runs on x86-64 so I'm not even sure how this would be possible?

Now that lambda supports both x86-64 and arm64, is there any plan of adding arm64 images?
