### ISSUE TITLE
Getting the return value out of the function?

### ISSUE THREAD

**Issue by justinmchase** [lambci/docker-lambda#25]
Suppose my function is:
```
export function example (input, context, callback) {
  callback(null, { result: 'success' })
}
```

And I'm invoking it via:
```
let cmd = `docker run --rm -v "$PWD/build/${app}":/var/task lambci/lambda handler.example '{}'
exec(cmd, (err, stderr, stdout) => {
  if (stderr && stderr !== 'null') console.log(`λ: (err)\n${stderr}`)
  if (stdout && stdout !== 'null') console.log(`λ: (out)\n${stdout}`)
  callback(err)
})
```

How can I get the value returned by the handler: `{ result: 'success' }`?

**Comment by mhart** [comment]
It should be the last line of stdout.

You might find it easier to use the `docker-lambda` npm package though:

```js
var dockerLambda = require('docker-lambda')

// Spawns synchronously, uses current dir – will throw if it fails
var lambdaCallbackResult = dockerLambda({event: {some: 'event'}})

// Manually specify directory and custom args
lambdaCallbackResult = dockerLambda({taskDir: __dirname, dockerArgs: ['-m', '1.5G']})
```

**Comment by justinmchase** [comment]
Ok I got it to work! I had a hard time getting it to work with dockerLambda due to some environment variables, I'm not sure what I was doing it wrong but I thought it would be easier to just do an exec myself. 

It turns out the problem I was having was that I had `stdout` and `stderr` mixed up on the output of exec. I didn't realize that docker was spitting out all output in stderr and returning the actual return result of the run in stdout. Once I understood that I am now able to get the return object, thanks for pointing me in the right direction.
