### ISSUE TITLE
Lambda Runtime Python 3.8 contains less packages than the Docker Image

### ISSUE THREAD

**Issue by eldos-dl** [lambci/docker-lambda#255]
The actual lambda runtime of Python 3.8 seems to contain a much lesser number of installed packages than Amazon Linux 2 AMI or docker image `lambci/lambda:build-python3.8 `

On actual lambda runtime, we are missing packages like `tar`.
Running the following code snippet on
```py
import os
print(os.listdir('/usr/bin'))
```

Lambda Python 3.8 Runtime: 156 results
Docker `lambci/lambda:build-python3.8 `:  685 results
Amazon Linux 2 AMI: 841 results

Output for Lambda Python 3.8:
```
["nohup",
  "mknod",
  "cat",
  "echo",
  "fgrep",
  "infotocap",
  "test",
  "pwd",
  "numfmt",
  "sprof",
  "bashbug",
  "truncate",
  "captoinfo",
  "printf",
  "fg",
  "shuf",
  "tzselect",
  "tail",
  "fc",
  "tabs",
  "getopts",
  "p11-kit",
  "chmod",
  "locale",
  "readlink",
  "chgrp",
  "cd",
  "tac",
  "nl",
  "ca-legacy",
  "tic",
  "infokey",
  "gencat",
  "command",
  "tty",
  "chcon",
  "sh",
  "gawk",
  "iconv",
  "unexpand",
  "dir",
  "yes",
  "fold",
  "infocmp",
  "arch",
  "od",
  "getent",
  "dd",
  "du",
  "ldd",
  "printenv",
  "sed",
  "realpath",
  "rmdir",
  "logname",
  "bashbug-64",
  "sha512sum",
  "users",
  "egrep",
  "getconf",
  "uniq",
  "link",
  "who",
  "date",
  "tsort",
  "hostid",
  "pldd",
  "dircolors",
  "touch",
  "cp",
  "split",
  "localedef",
  "mv",
  "base64",
  "ls",
  "csplit",
  "sha224sum",
  "update-ca-trust",
  "basename",
  "wait",
  "tset",
  "mkfifo",
  "tr",
  "nproc",
  "true",
  "stty",
  "stdbuf",
  "groups",
  "install",
  "dgawk",
  "mkdir",
  "dirname",
  "chown",
  "sha384sum",
  "alias",
  "cut",
  "false",
  "sha1sum",
  "igawk",
  "join",
  "clear",
  "shred",
  "rpcgen",
  "reset",
  "bg",
  "whoami",
  "nice",
  "awk",
  "read",
  "vdir",
  "sum",
  "tput",
  "bash",
  "md5sum",
  "toe",
  "sync",
  "id",
  "makedb",
  "info",
  "unalias",
  "df",
  "sotruss",
  "sha256sum",
  "timeout",
  "[",
  "fmt",
  "factor",
  "tee",
  "sort",
  "expr",
  "ln",
  "rm",
  "trust",
  "env",
  "paste",
  "jobs",
  "runcon",
  "catchsegv",
  "pgawk",
  "pinky",
  "mktemp",
  "umask",
  "sleep",
  "stat",
  "pathchk",
  "uname",
  "pr",
  "unlink",
  "wc",
  "expand",
  "ptx",
  "cksum",
  "seq",
  "grep",
  "head",
  "comm"
]
```

**Comment by mhart** [comment]
This is correct – if you check on production Lambda you'll see it's also missing those packages. (this is why I created the build-* images in the first place – so they could have everything from the base Lambda as well as building tools)

Check out https://github.com/lambci/yumda if you need extra binaries and libraries on your Lambda

**Comment by fred-vogt** [comment]
@eldos-dl - The non `build-` version of the image matches the AWS 3.8 lambda runtime:
```
docker run -it --rm --entrypoint bash lambci/lambda:python3.8
bash-4.2$ ls -l /usr/bin | wc -l
157
```
* https://github.com/lambci/docker-lambda/blob/master/python3.8/run/Dockerfile
* https://github.com/lambci/docker-lambda/blob/master/base/base-2/packages.txt

@mhart - this is a fantastic project and a big time saver.
The new AWS runtimes are a pain to migrate to, your build images really help in creating "layers" to restore compatibility with the older kitchen sink lambda runtimes.
