### ISSUE TITLE
How to enable CORS

### ISSUE THREAD

**Issue by laynr** [lambci/docker-lambda#256]
How  to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) support? Or in other words, how to add the header "Access-Control-Allow-Origin" with the value "*" to the response header of the lambda function?  

AWS Documentation
- https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html
- https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-gateway-response-using-the-console.html

**Comment by mhart** [comment]
CORS support in what? Are you sure you're asking in the right repo?

**Comment by laynr** [comment]
Yes, I am asking for CORS support in lambci/docker-lambda

*Steps:*
1. Start up a lambda: docker run --rm -d -e DOCKER_LAMBDA_STAY_OPEN=1 -p
9001:9001 lambci/lambda:python3.8
2. View the headers (*use -i in curl*):  curl *-i *-d '{}'
http://localhost:9001/2015-03-31/functions/myfunction/invocations

*Response:*
HTTP/1.1 200 OK
Content-Length: 124
Content-Type: application/json
X-Amz-Executed-Version: $LATEST
X-Amz-Function-Error: Unhandled
X-Amzn-Remapped-Content-Length: 0
X-Amzn-Requestid: 0364ebe2-ae36-1dd6-5466-2e598d005f6f
X-Amzn-Trace-Id:
Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1
Date: Thu, 05 Mar 2020 17:02:17 GMT

*Desired Response:*
HTTP/1.1 200 OK
Content-Length: 124
Content-Type: application/json
*Access-Control-Allow-Origin: * *
X-Amz-Executed-Version: $LATEST
X-Amz-Function-Error: Unhandled
X-Amzn-Remapped-Content-Length: 0
X-Amzn-Requestid: 0364ebe2-ae36-1dd6-5466-2e598d005f6f
X-Amzn-Trace-Id:
Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1
Date: Thu, 05 Mar 2020 17:02:17 GMT

*Why:*
Enabling CORS in the lambda response will enable testing of web
applications that call lambda functions.
"The use-case for CORS is simple. Imagine the site alice.com has some data
that the site bob.com wants to access. This type of request traditionally
wouldn’t be allowed under the browser’s same origin policy. However, by
supporting CORS requests, alice.com can add a few special response headers
that allows bob.com to access the data." - more info here
<https://www.html5rocks.com/en/tutorials/cors/> (
https://www.html5rocks.com/en/tutorials/cors/)

**Comment by mhart** [comment]
Reason I asked was because you linked to API Gateway documentation.

I'll have a think about this. I think the official API includes CORS headers, which is a good reason to duplicate it. Thanks for the suggestion 👍

**Comment by unstableunicorn** [comment]
Can I please second this request.
I am testing web pages and this is perfect for local testing and ci tests except that CORS is currently not allowed and we can't use it.
All our lambda's are api end points for a webpage.

**Comment by mhart** [comment]
Thanks for the nudge – this should be enabled in the latest images – let me know if it works for you!

**Comment by unstableunicorn** [comment]
That's great! I'll try them today.  
I actually forked the repo last night and was going to have a go at making the changes today so this saves me a lot of time.

**Comment by unstableunicorn** [comment]
Finally got around to this today, still have CORS issues, although now it is content-type:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9001/2015-03-31/functions/my_handler/invocations. (Reason: header ‘content-type’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

My request headers are:
```
Host: localhost:9001
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: */*
Accept-Language: en-AU,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://localhost:55990/
Origin: http://localhost:55990
DNT: 1
Connection: keep-alive
```
Current response headers:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date,x-amz-log-result,x-amz-function-error
Access-Control-Max-Age: 172800
X-Amzn-Requestid: 4f38ccb2-6764-1732-86b5-f02fb28a4202
Date: Tue, 30 Jun 2020 03:28:11 GMT
Content-Length: 0
```

**Comment by mhart** [comment]
I wonder if this is the OPTIONS request that's at fault. I've just made some changes – try again now

**Comment by unstableunicorn** [comment]
This is now working nicely, thank you!

**Comment by shyal** [comment]
Still an issue here. Kind of surprised these are my headers. 

```
HTTP/1.1 200 OK
Content-Length: 705
Content-Type: application/json
X-Amz-Executed-Version: $LATEST
X-Amzn-Remapped-Content-Length: 0
X-Amzn-Requestid: 962f668c-ef02-121c-ac61-30dd5112511a
X-Amzn-Trace-Id: Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1
Date: Fri, 29 Jan 2021 10:26:18 GMT
```

**Comment by mhart** [comment]
@shyal are you using docker-lambda? If not, this is the wrong repo

**Comment by shyal** [comment]
Yeah i'm sure. :)

**Comment by mhart** [comment]
@shyal how are you making the request? CORS headers were added a while ago

**Comment by mhart** [comment]
(specifically, what Origin header are you sending?)
