### ISSUE TITLE
Docs use "$PWD" which seems to fail silently

### ISSUE THREAD

**Issue by rmjjjt** [lambci/docker-lambda#258]
I don't know if this is down to my understanding of $PWD, pwd, $(PWD), but whenever I come back to check the build script (I mean to copy and paste it), I trip up because they don't work.

Silently fail: `docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm rebuild`
Success: `docker run --rm -v "$(PWD)":/var/task lambci/lambda:build-nodejs12.x npm rebuild`

I'm quite happy to put in a quick pr to change the docs, but wanted to check it isn't my misunderstanding causing the problem first!

**Comment by mhart** [comment]
What operating system are you on? `PWD` is a standard unix env variable

**Comment by rmjjjt** [comment]
On mac.

**Comment by mhart** [comment]
What does `echo $PWD` say?

**Comment by rmjjjt** [comment]
It gives the pwd correctly.
What made me notice the problem was that if I run the example, I get this output:
`docker run --rm -v WD:/var/task lambci/lambda:build-nodejs12.x npm rebuild --build-from-source`
Notice the `WD` being substituted from `"$PWD"`. When I put the brackets around it, I end up with the correct pwd substituted in.

**Comment by mhart** [comment]
And `echo "$PWD"` works ok?

When you're using brackets, you're invoking `/bin/PWD` – which is a much less standard thing to do

**Comment by mhart** [comment]
Something is definitely weird – either the quotes are a bit strange, or your terminal isn't showing the command correctly while you're editing it (and hence you end up editing the wrong part), or something like that

**Comment by rmjjjt** [comment]
Yes - if I use that in the terminal `echo "$PWD"` returns the correct location.

Thanks for clearing up the bin part - as I said, I don't know if it was my misunderstanding of different pwd commands.

Maybe it is an anomaly on my system. 🤷‍♂

**Comment by mhart** [comment]
How about this?

```
echo docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm rebuild
```

**Comment by rmjjjt** [comment]
That works. I think I see the problem - we wrap the build command in a makefile. This is to do with the makefile PWD.

**Comment by rmjjjt** [comment]
Thanks for your help @mhart. I will close the issue.
