### ISSUE TITLE
Rust Custom Runtime error - JsonError: missing field 'path'

### ISSUE THREAD

**Issue by realharry** [lambci/docker-lambda#259]
I'm trying out the rust runtime with `lambci/lambda:provided`. The lambda function runs fine on AWS lambda (behind the API gateway, with lambda-proxy integration). But, I get the following error on docker-lambda:
```
{"errorType":"JsonError","errorMessage":"JsonError: missing field `path` at line 1 column 24"}
```

This is how I test it:
```
curl -d '{}' http://localhost:9001/2015-03-31/functions/myfunction/invocations
```

The same result with `aws lambda invoke ...`

This is how I start the docker container (based on the example doc):
```
docker run --rm \
  -e DOCKER_LAMBDA_STAY_OPEN=1 \
  -p 9001:9001 \
  -v /home/harry/.../my-lambda/target/x86_64-unknown-linux-musl/release:/var/task:ro,delegated \
  lambci/lambda:provided
```

Quick experimentation reveals that the runtime expects params like "path", "httpMethod", "headers", "queryStringParameters", "requestContext", ...

I don't remember I had to process these "envelope" information in other runtimes (like Node.js). Even in Rust custom runtime (https://github.com/awslabs/aws-lambda-rust-runtime), I only process the body. Not sure where the error lies, but it looks like the "provided" runtime expects these envelope information?

Thanks.

**Comment by mhart** [comment]
It doesn't expect that information by default – it's because you've created your rust program to expect an API Gateway event.

If you invoke your live Lambda the same way (ie, use `aws lambda invoke ...`) with an empty body you'll see you get the same error.

You need to pass an event in that resembles an API Gateway event – docker-lambda doesn't emulate API Gateway, it emulates Lambda only. See here for an example event that API Gateway sends Lambda when it's invoked:

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

**Comment by realharry** [comment]
Hi @mhart Yes, you are right. I do remember I had to start writing my lambdas slightly different since I started using API gateway, ALB, etc. (I completely forgot about that.) Actually, calling my Lambdas directly (either via aws cli or from lambda console) works just fine. That was why I was confused. AWS knows that my lambdas are integrated with lambda-proxy and they add that information automatically (as if the request is coming from APIGW/ALB). I presume asking for that in docker-lambda might be too much. Thanks for the great work. Docker-lambda could have been very useful for me.

**Comment by mhart** [comment]
> Actually, calling my Lambdas directly (either via aws cli or from lambda console) works just fine. That was why I was confused. AWS knows that my lambdas are integrated with lambda-proxy and I suppose they add that information automatically 

I don't think this is true. Can you show me an example with `aws lambda invoke ...`?

**Comment by realharry** [comment]
This is a simple "echo" lambda integrated with API gateway. The same behavior with ALB integration.

Calling Lambda directly:
```
harry@fiji:~/Projects/.../infra1-api-lambdas$ aws lambda invoke --endpoint https://xxxx.execute-api.us-west-2.amazonaws.com/alpha/  --function-name Inf1AlphaConcertbarnjoinA-lambdaInf1AlphaConcertba-aaa --payload '{"signupEmail": "harry@example.com"}' output.json
{
    "StatusCode": 200
}
harry@fiji:~/Projects/.../infra1-api-lambdas$ cat output.json 
{"signupEmail": "harry@example.com"}
```

Calling the API endpoint:
```
harry@fiji:~/Projects/.../infra1-api-lambdas$ curl https://xxxx.execute-api.us-west-2.amazonaws.com/alpha/ -d '{"signupEmail": "harry@example.com"}'
{"signupEmail": "harry@example.com"}
```

**Comment by mhart** [comment]
You’re not calling Lambda directly when using the —endpoint argument - you’re calling your API Gateway proxy endpoint. Remove that argument and see what happens

**Comment by realharry** [comment]
yes, you are right. without `--endpoint`, it expects the same envelope information. I can always add a fake envelope when I test my lambdas locally. (then again, I presume it can be easily added to docker-lambda with a certain flag?) anyways, thanks.
