### ISSUE TITLE
lambci/lambda:python3.7 Issues importing lxml and etree

### ISSUE THREAD

**Issue by tcco** [lambci/docker-lambda#263]
This container is unable to import lxml, a pre-req to zeep. Is there a way to either compile libxml2 and libxslt in container? lxml is part of the distribution but it is referencing one in `/var/task/`. Is this where the distribution is loaded in container or is this another? 

```
cannot import name 'etree' from 'lxml' (/var/task/lxml/__init__.py)"}
```

Similar related issues
[serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements/issues/432)

**Comment by mhart** [comment]
The non-build containers are a replica of the live Lambda environment – it looks from that issue like the same error is happening on Lambda, so I don't think it's an issue with this image?

**Comment by tcco** [comment]
So this actually isn't occurring on the lambda itself, which is the concern. We're using AWS SAM to build/package (& sam local start-api locally). Those only difference is OS when generating the distribution, locally am on OSX whereas in Code Build is Ubuntu

**Comment by mhart** [comment]
Can you explain the steps? The issue you linked to says `After uploading and running lambda function...`

**Comment by tcco** [comment]
Apologies my use case is locally running `sam local start-api`

Simplified steps to reproduce (app.py being a chalice or flask app)
```
pip install zeep (any library with lxml as a prereq) -t ./dist
cp app.py ./dist
# CodeUri: ./dist, Handler: app.lambda_handler, Runtime: python3.7
sam local start-api
curl 127.0.0.1:3000/info
```

That will result in the original error message, using lambci/lambda:python3.7 image
`cannot import name 'etree' from 'lxml' (/var/task/lxml/__init__.py)"}`

**Comment by mhart** [comment]
If you're not running `pip install` in a Linux environment, then it's going to install MacOS native dependencies isn't it?

Have you tried using the build images? eg, `lambci/lambda:build-python3.7`

**Comment by tcco** [comment]
You're correct - I have not tried build images. Would this be along the lines of what I'd need to run?

`docker run -v "$PWD":/var/task "lambci/lambda:build-python3.7" /bin/sh -c "pip install -r requirements.txt -t ./dist; exit"`

**Comment by mhart** [comment]
Yeah, I think so – can probably just make it:

```
docker run -v "$PWD":/var/task "lambci/lambda:build-python3.7" \
  pip install -r requirements.txt -t ./dist
```

**Comment by tcco** [comment]
thanks @mhart that did the trick. Had to install one additional native dep in `unixODBC-devel` but was able to pip install properly with the build container. Closing

**Comment by tcco** [comment]
Hey sorry 

so i was able to properly install my requirements, zeep included by running
```
docker run -v "$PWD":/var/task lambci/lambda:build-python3.7 \
yum install -y unixODBC-devel && \
pip install -r src/ls/requirements.txt -t ./dist/ && \
cp -r src/* dist/
```

However when running `sam local start-api` i still run into the issue of `cannot import name 'etree' from 'lxml' (/var/task/lxml/__init__.py)`

**Comment by mhart** [comment]
That command can't be right? If it were, you'd be running `yum install` on your Mac...

**Comment by mhart** [comment]
In any case, even if you were running all those command within the container (eg using `sh -c`), you're still going to have the issue that you'll need to bundle any native libraries you need (eg `unixODBC`). These will need to exist in a path accessible by Lambda

**Comment by tcco** [comment]
Command ran alright. And yeah, I figure i'll have to extract native libs and bundle. Thanks again

**Comment by saigokarakonda1** [comment]
@tcco  have you figured out the issue. i am facing same issue on this, could you please post your solution?
