### ISSUE TITLE
Support to uber jar files

### ISSUE THREAD

**Issue by csgui** [lambci/docker-lambda#274]
Hello all! Just a question...

I am planning to use Kotlin to develop a Lambda function. Can I use an uber jar in docker-lambda to check my implementation?

Thanks.

**Comment by mhart** [comment]
I believe it should work fine – it uses the same class loader as AWS Lambda does, so it should give you an indication of whether it will work on Lambda or not

**Comment by csgui** [comment]
Just did a test and seems to be working.

To keep as note, what I did:

- extracted the uber jar content in a folder

- running `$ docker run --rm ...etc` from that folder 

- compiled Kotlin code is running ok

**Comment by mhart** [comment]
🙌
