### ISSUE TITLE
LambdaContext giving negative time remaining

### ISSUE THREAD

**Issue by AdamLewisGMSL** [lambci/docker-lambda#281]
When running a lambda with DOCKER_LAMBDA_STAY_OPEN, each time you invoke the lambda the RemainingTime property decreases as it appears to base the StartTime from the moment you started hosting the lambda, not from the moment you started the execution. Keep it going long enough and you get a negative RemainingTime result.

Suspect this is to do with MockLambdaContext.cs

**Comment by mhart** [comment]
Which runtime is this for?

**Comment by AdamLewisGMSL** [comment]
2.1

**Comment by mhart** [comment]
Gotcha – will look into it, thanks

**Comment by mhart** [comment]
Fixed in https://github.com/lambci/docker-lambda/commit/5ca3009aebfe1fe05e5c5aebec4a96b4648beb08
