### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by petervaro** [lambci/docker-lambda#29]
**Feature request:** According to the [Release: AWS Lambda on 2017-4-18](https://aws.amazon.com/releasenotes/5198208415517126) Python 3.6 support has finally arrived. So it would be beneficial to add support for this version in `lambci` as well. Cheers!

**Comment by mhart** [comment]
Hasn't arrived yet!

```
An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Value python3.6 at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, nodejs, nodejs4.3, python2.7, dotnetcore1.0]
```

**Comment by mhart** [comment]
See also: 
![lambda-select](https://cloud.githubusercontent.com/assets/367936/25185397/3ed97f6a-24eb-11e7-80e7-682158ee2457.png)

**Comment by petervaro** [comment]
interesting, well it should be available in the next 24 hours I guess.. shouldn't it?

**Comment by mhart** [comment]
I guess. Kinda annoying they've been talking about it for the last day before they've even released it

**Comment by petervaro** [comment]
anywho, thanks for the extremely quick reply! now we only have to wait then.. :)

**Comment by petervaro** [comment]
it looks like `us-east-2` and `eu-west-1` already has it! ![screen_shot_2017-04-19_at_16 01 22](https://cloud.githubusercontent.com/assets/2691101/25187017/c8eaaee4-2519-11e7-9983-97bbc9471c34.png)

**Comment by jneves** [comment]
I suspect this may be fixed by https://github.com/lambci/docker-lambda/commit/2cd8df4d844a1b73814b9824bad8cca77c3e040a

**Comment by mhart** [comment]
@jneves oh right – forgot this was still open – thanks for the nudge!
