### ISSUE TITLE
use aws sdk with custom endpoint that points to local docker lambda container

### ISSUE THREAD

**Issue by varunudacity** [lambci/docker-lambda#30]
I'm using the go aws sdk. It allows me to customize the endpoint for lambda, e.g., localhost:8000. Will the docker container given here respond to aws lambda invoke commands, as expected, if I do this?

**Comment by derickson82** [comment]
+1

**Comment by joovel** [comment]
I threw something together to do this but it's heavily dependent on our environment. We use node. The basic idea is that I use the Docker Remote API to run this image, mounting my code at /var/task. The HTTP server has to respond to POST on `/:date/functions/:functionName/invocations`. 

Another example is here: https://github.com/luisfarzati/docker-lambda-api-server

**Comment by binarymist** [comment]
I'm just getting started with the aws sdk, and I need to dev and test lambda functions locally, It seems like this project may work for that? I'm seeing here (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/specifying-endpoints.html) that I can specify an endpoint, not sure how to do this for lambda though yet? Any tips on how to set the lambda endpoints if I'm going to dev and test on docker-lambda? Is this how docker-lambda is supposed to be used?

Thanks.

**Comment by binarymist** [comment]
Seems like aws-sam-cli works well enough
