### ISSUE TITLE
Upgrade node12.x to v12.18.2 to support ES Modules without a flag

### ISSUE THREAD

**Issue by alekseykulikov** [lambci/docker-lambda#300]
AWS recently upgraded `node12.x` to `v12.18.2`. It means it supports ES Modules without a flag 🎉 

ES Modules support starts since `v12.17.x`, and Lambci is `v12.16.3`, which matches the previous version of `node12.x`.

AWS Lambda version:

```js
exports.handler = async (event) => {
    return process.version; // v12.18.2
};
```

Lambci version:

```bash
$ docker run --rm --entrypoint node lambci/lambda:nodejs12.x -v
v12.16.3
```

**Comment by mhart** [comment]
You're right, but this update is in the process of being rolled out – it hasn't rolled out to all regions yet (for example, it hasn't rolled out to `ap-southeast-2` yet).

It should be finished in the next few days, but there's a chance it will be rolled back too, if issues are encountered in other regions.

I'll let you know when it's finalized and I've pushed up updated images

**Comment by mhart** [comment]
Took a while, but it finally rolled out to all regions this morning! I've since updated the images 👍

**Comment by alekseykulikov** [comment]
thank you 🙏
