### ISSUE TITLE
java8.al2 libcurl package is missing

### ISSUE THREAD

**Issue by r1m** [lambci/docker-lambda#319]
I'm running a java8 lambda that uses some native lib through JNI.
It works on AWS, but using `lambci:java8.al2` it fails because libcurl is missing.
libcurl can be found in amazonlinux2 and must be present in AWS lambda env.

`docker run -it --entrypoint sh lambci/lambda:java8 -c 'ls /lib64'` shows no libcurl so files

**Comment by mhart** [comment]
To clarify, are you running `java8.al2` or `java8` on AWS? They're different runtimes

**Comment by r1m** [comment]
Right, I was thinking it was only a change in your base image. So I tried both.
But `java8` is my runtime on AWS.

**Comment by mhart** [comment]
Well on `java8` libcurl is installed. It's in `/usr/lib64`

**Comment by mhart** [comment]
It's not on `java8.al2` – but that's because it's not on the `java8.al2` runtime on AWS either. You can use something like https://github.com/lambci/yumda to install it in a layer

**Comment by r1m** [comment]
Ok, I was confused by some localstack configuration. Thanks for your quick answer and clarification.
