### ISSUE TITLE
Provide event data via json file 

### ISSUE THREAD

**Issue by estahn** [lambci/docker-lambda#35]
It would be helpful to provide the event data via a file.

Current workaround:
```bash
docker run -v "$PWD":/var/task lambci/lambda index.handler "$(jq -M -c . event-create.json)"
```

**Comment by mhart** [comment]
You shouldn't need `jq` for that – should just be able to `"$(cat event-create.json)"`

I think for the sake of brevity there's no need to add an option for this, so I'll close for now.

If there are some more complex cases that can't be handled with just a simple `cat`, let me know and I'll look into it.
