### ISSUE TITLE
yum install issues in the build version

### ISSUE THREAD

**Issue by cscetbon** [lambci/docker-lambda#38]
Hey,

when trying to install yum packages I get issues https://pastebin.com/H0rgSD6u
It's a known issue on centOS https://github.com/CentOS/sig-cloud-instance-images/issues/15#issuecomment-252563831 but I can't install the needed package to make it work on alpine

**Comment by mhart** [comment]
@cscetbon I wonder if this is just an issue with Docker? https://github.com/moby/moby/issues/10180

Try running `rpm --rebuilddb` before your yum installs and see if that works.

**Comment by cscetbon** [comment]
@mhart `rpm --rebuilddb` completely fixes the issue. So I can't see any reason it'd be a docker issue

**Comment by mhart** [comment]
I believe it might be a docker issue with overlayfs - the rpm rebuild solution was suggested on that docker issue I linked to

**Comment by cscetbon** [comment]
Yeah I saw. I just checked and I'm using overlayfs2
```
Server Version: 17.03.1-ce
Storage Driver: overlay2
```
So could be but no one seems to have an explanation ...

**Comment by cscetbon** [comment]
FYI @mhart I just confirmed that I don't get any issue with aufs.
