### ISSUE TITLE
how to mount file credentials from host to container?

### ISSUE THREAD

**Issue by pahud** [lambci/docker-lambda#4]
Hi,

Can I mount my **$HOME/.aws**  into Docker container to share my AWS config/credentials and have my code like this:

```
console.log('starting lambda')

var AWS = require("aws-sdk");
AWS.config.update({region: 'us-west-2' });


if (process.env.IN_DOCKER_LAMBDA) {
  var credentials        = new AWS.SharedIniFileCredentials({profile: 'myprofile'});
  AWS.config.credentials = credentials;
  AWS.config.update({region: 'us-west-2' });
}
```

In this case the **docker-lambda** will just load the credentials in shared ini while in real AWS lambda it will just retrieve credentials from the EC2 metadata. And I don't have to hardcode my credentials in the code.

idea?

**Comment by pahud** [comment]
Well,

Now I configure my credentials in this file and **chmod 0600** on it
```
$ cat $HOME/.aws/projet_docker_credentials 
AWS_ACCESS_KEY_ID=****
AWS_SECRET_ACCESS_KEY=****
```

```

docker run \
--env-file ~/.aws/project_docker_credentials \
-v "$PWD":/var/task lambci/lambda

```

Now it works fine :-)

**Comment by mhart** [comment]
Yeah, apologies for the lack of documentation at the moment – but all of the env variables mentioned here can be used by the container in the same way they are on Lambda: https://github.com/lambci/docker-lambda#documentation

So you can either pass them manually to `docker run` as you've done – or, if they're already in your env, then you can just do `dockerLambda({addEnvVars: true})` – and you can see that all of those variables will be passed to the command line: https://github.com/lambci/docker-lambda/blob/master/index.js#L35

**Comment by mhart** [comment]
Going to close this as it seems solved – the larger issue of the lack of documentation is on my TODO though 👍

**Comment by haydenk** [comment]
```
docker run -i --rm \
    -v $HOME/.aws:/home/sbx_user1051/.aws \
    -v $PWD:/var/task \
    -e AWS_PROFILE=personal \
    lambci/lambda:python3.6 app.lambda_handler
```

This would make it like how you do it outside of Docker as well as make it easier to switch to a different AWS_PROFILE for different credentials.
