### ISSUE TITLE
nodejs shim is missing reportException() method

### ISSUE THREAD

**Issue by sanathkr** [lambci/docker-lambda#41]
I am getting `TypeError: awslambda.reportException is not a function` when returning a non-null error through callback method. I suspect the nodejs shim is missing reportException() function.

I can repro on both nodejs4.3 and nodejs6.10

**index.js file**
```
exports.handler = function(context, event, callback) {
    return callback('error')
}
```

**docker output**
```
docker run -v "$PWD":/var/task lambci/lambda:nodejs6.10

START RequestId: fcf8ab72-c8b0-133b-2fc4-225a8173b1fe Version: $LATEST
2017-07-01T06:29:11.741Z	fcf8ab72-c8b0-133b-2fc4-225a8173b1fe	{"errorMessage":"error"}
2017-07-01T06:29:11.745Z	fcf8ab72-c8b0-133b-2fc4-225a8173b1fe	TypeError: awslambda.reportException is not a function
```

**Comment by mhart** [comment]
This was fixed in 7299a68c092509a0e860612c45c81d5749c57252 – let me know if it's all working for you now 👍
