### ISSUE TITLE
Question: How would i use this docker-lambda to build code?

### ISSUE THREAD

**Issue by sandeepzgk** [lambci/docker-lambda#44]
I am fairly new to docker, hence the noob question. I have installed docker and am able to execute basic lambda and it runs and exits promptly as expected.

1. How would i bundle a bunch of code (c, js, cpp) to this docker to build and give me zip artifacts from this docker so that i can use it to deploy in my real lambdas. An example would be greatly appreciated.

2. I tried to run to find out the gcc version in this docker, and it reports it doesnt have gcc nor does it have zip. how would i go about installing them in this docker? or am i using the wrong docker?

How am i running ( i have an index.js in the pwd)
sudo docker run -v "$PWD":/var/task lambci/lambda:nodejs6.10 (probably i need to run something else other than :nodejs6.10)

**Comment by sandeepzgk** [comment]
I found the errors of my way

I should have used build-nodejs6.10 tag, and have got into the container by 
sudo docker run -it lambci/lambda:build-nodejs6.10 /bin/bash

**Comment by mhart** [comment]
You'll probably find everything you need in the build images – so for Node.js 6.10 that would mean running `lambci/lambda:build-nodejs6.10`

**Comment by mhart** [comment]
Ah yes, you just found that 👍
