### ISSUE TITLE
Availability of node-gyp in build version of dockers

### ISSUE THREAD

**Issue by sandeepzgk** [lambci/docker-lambda#45]
One important artifact that is missing from the lambda docker build image is node-gyp

**Comment by mhart** [comment]
@sandeepzgk I'm not sure what you mean?

```bash
$ find / -name node-gyp
/var/lang/lib/node_modules/npm/bin/node-gyp-bin/node-gyp
/var/lang/lib/node_modules/npm/node_modules/node-gyp
/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/bin/node-gyp-bin/node-gyp
/usr/local/lib64/node-v4.3.x/lib/node_modules/npm/node_modules/node-gyp
```

```bash
$ npm install hiredis

> hiredis@0.5.0 install /var/task/node_modules/hiredis
> node-gyp rebuild

make: Entering directory `/var/task/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory `/var/task/node_modules/hiredis/build'
/var/task
└─┬ hiredis@0.5.0 
  ├── bindings@1.2.1 
  └── nan@2.6.2 

```

**Comment by mhart** [comment]
Going to close this, because node-gyp is definitely in the Node.js build images – but if you're seeing a specific error that you think is from something missing, let me know and I'll be happy to reopen.

**Comment by sandeepzgk** [comment]
i am not able to use node-gyp on the build-node6.10 image. I am installing it manually.

**Comment by sandeepzgk** [comment]
Here are the custom things i find necessary that are missing in the  lambci/lambda:build-nodejs6.10 image

## install node-gyp
npm install -g node-gyp

# install wget
yum install wget -y
yum install curl-devel -y

**Comment by mhart** [comment]
@sandeepzgk it's already on the image. You can see it in use if you install a native dependency as I showed here: https://github.com/lambci/docker-lambda/issues/45#issuecomment-314530791

See the `node-gyp rebuild` step?

**Comment by mhart** [comment]
If you're having problems, please paste the output of running the following command:

```console
docker run lambci/lambda:build-nodejs6.10 npm install hiredis
```
