### ISSUE TITLE
pkg-config prefix is incorrect

### ISSUE THREAD

**Issue by joshua** [lambci/docker-lambda#49]
I'm using the `lambci/lambda:build-python3.6` image to build a python C module. The prefix value in python-3.6 pkg-config file is incorrect.

The current value is:

`/local/p4clients/pkgbuild-cuFpW/workspace/build/LambdaLangPython36/LambdaLangPython36-x.21.4/AL2012/DEV.STD.PTHREAD/build`

It should be `/var/lang`.

Adding the following to my Dockerfile corrects the issue:

```
sed -i '/^prefix=/c\prefix=/var/lang' /var/lang/lib/pkgconfig/python-3.6.pc
```

Here is the full file for reference: `/var/lang/lib/pkgconfig/python-3.6.pc`

```
# See: man pkg-config
prefix=/local/p4clients/pkgbuild-cuFpW/workspace/build/LambdaLangPython36/LambdaLangPython36-x.21.4/AL2012/DEV.STD.PTHREAD/build
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Python library
Requires:
Version: 3.6
Libs.private: -lpthread -ldl  -lutil -lrt
Libs: -L${libdir} -lpython3.6m
Cflags: -I${includedir}/python3.6m
```

**Comment by mhart** [comment]
Ah, nice pickup – that must be what it is on Lambda in production and it's not getting overridden when I build the dev tools:

https://github.com/lambci/docker-lambda/blob/master/python3.6/build/Dockerfile#L9-L13

Will address this and let you know when it's fixed 👍

**Comment by mhart** [comment]
@joshua actually, just to clarify – were you getting an error of some sort trying to run a command? Or were you just pointing out that `python-3.6.pc` didn't have the `/var/lang` prefix?

If it's just the latter then I might not change it – considering that this is the value that exists on Lambda itself, it's a more faithful reproduction to leave it as is.

**Comment by mhart** [comment]
@joshua never mind my previous comment 😄  I went ahead and fixed this in https://github.com/lambci/docker-lambda/commit/4bd63c20a912523a829f95cab86a11035f1aab47 (as well as including `/var/lang/lib/pkgconfig` in `PKG_CONFIG_PATH` and matching the same set of LIBS that the Lambda version of python 3.6 is built with)

**Comment by joshua** [comment]
Awesome. I forgot to mention that I modified `PKG_CONFIG_PATH` also.

Thanks for the quick turn around. I'll update my images.
