### ISSUE TITLE
Loading github credentials 

### ISSUE THREAD

**Issue by pierrerappolt** [lambci/docker-lambda#50]
I am using the command:
`docker run -v "$PWD":/var/task lambci/lambda:build-nodejs4.3 npm install`

but getting the error:
`Host key verification failed.`

The problem lies in attempting to access some of my dependencies thru SSH'ing into github. 
Where should I be putting my credentials to make this work?

**Comment by mhart** [comment]
Putting them in `/root/.ssh` on the container should work. Something like this might work:

```
docker run -v "$PWD":/var/task -v "$HOME/.ssh":/root/.ssh lambci/lambda:build-nodejs4.3 npm install
```

You can play around manually in the container and see what works:

```
docker run -it lambci/lambda:build-nodejs4.3 bash
```
Or this if you want to expose your own .ssh directory in the container:
```
docker run -v "$HOME/.ssh":/root/.ssh -it lambci/lambda:build-nodejs4.3 bash
```

**Comment by pierrerappolt** [comment]
Wow so helpful thank you! @mhart

**Comment by mhart** [comment]
@pierrerappolt no probs, did that solve your problem?

**Comment by pierrerappolt** [comment]
I'm getting this error at the moment

```
npm ERR! /root/.ssh/config: line 2: Bad configuration option: addkeystoagent
npm ERR! /root/.ssh/config: line 3: Bad configuration option: usekeychain
npm ERR! /root/.ssh/config: terminating, 2 bad configuration options
```

**Comment by pierrerappolt** [comment]
I tried changing my ~/.ssh/config file to 

```
Host *
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile /root/.ssh/id_rsa
```
but still no luck

**Comment by mhart** [comment]
@pierrerappolt right, they're probably macOS-specific settings that don't work on Linux.

Might be best just to connect the files you need then instead of the whole `.ssh` directory

**Comment by pierrerappolt** [comment]
@mhart Is there a way I can run `npm install` from within bash?

**Comment by pierrerappolt** [comment]
I am able to create new working github permissions within bash but then can't run npm install

**Comment by mhart** [comment]
Not sure what you mean? What happens when you run npm install?

**Comment by pierrerappolt** [comment]
@mhart 
after doing:
`docker run -v "$HOME/.ssh":/root/.ssh -it lambci/lambda:build-nodejs4.3 bash`

`no such file or directory, open '/var/task/package.json'`

**Comment by pierrerappolt** [comment]
`bash-4.2# npm install` in between those

**Comment by mhart** [comment]
Right – so the `-v` option to docker is used to expose your local directories on the docker container. So you'll need `-v "$PWD":/var/task` if you want to expose your (current) project directory

**Comment by pierrerappolt** [comment]
@mhart Doh! Solved! Thank you so much!

**Comment by mhart** [comment]
No probs, glad it worked for you 👍
