### ISSUE TITLE
Triggers to run Lambda Function

### ISSUE THREAD

**Issue by mikebrules** [lambci/docker-lambda#53]
Hello,

I'm trying to find a solution to run a Lambda function locally based on a "Dynamo Stream" Trigger. I've looked at the SAM local work, but that only allows one-off executions of a function (via the `invoke` command.) 

This docker environment looks ideal, but I don't think there is scope here to define a trigger. Am I right? Is there a way of achieving this locally anyone can think of?

**Comment by mhart** [comment]
What do you mean by "define a trigger"?

Do you mean you want to create a trigger from a live DynamoDB instance and have it run a Lambda locally? If so, then you're right, that's not possible.

The closest way to do it off the top off my head would be to trigger a lightweight Lambda function that's just a passthrough/proxy to a known address that you expose a local http server on that invokes your local lambda. ie, DynamoDB Stream->Lambda->Local Server->Local Lambda

**Comment by mikebrules** [comment]
hi @mhart thanks for getting back - no, I wanted to run it all locally (local dynamo, local lambda) so I can replicate "live" behaviour. I figured there might be a way to do it by starting a local node app that consumes the dynamo stream of my local lambda, and call  the sam local "invoke" method on my local lambda, passing it the payload dynamo event? Maybe?

**Comment by mikebrules** [comment]
In "real life" the AWS Lambda polls Dynamo on your behalf, so I guess this is an approximation of that

**Comment by mhart** [comment]
Right, there's nothing out of the box that can do that locally I don't think – https://github.com/localstack/localstack would be the nearest candidate. it's outside the scope of this project for sure. But certainly should be possible to build something!

**Comment by mikebrules** [comment]
thanks loads @mhart

**Comment by theowenyoung** [comment]
@mikebrules Hi, I think [aws](https://github.com/awslabs/aws-sam-cli) can support local api gateway, it also use the lambda-docker as lambda local runtime. 

but it need a docker socket dependence, I need a only docker normal dependence solution,

so here is my solution： https://github.com/theowenyoung/aws-lambda-docker-local-example
