### ISSUE TITLE
Add dependencies for python

### ISSUE THREAD

**Issue by johnjelinek** [lambci/docker-lambda#54]
How do you add dependencies for python from pip?

For example, for lambda, I can do `pip install ... -t lambda` and my imports are included in the package and all resolve. This doesn't seem to work with docker-lambda.

**Comment by mhart** [comment]
When you say it doesn't seem to work, how are you running docker-lambda and how are you mounting your project directory onto `/var/task`?

If you match the [same layout as the zipfile expects](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html), and mount that directory on `/var/task`, it should work fine.

**Comment by johnjelinek** [comment]
I see the problem ... I needed to put all my deps in the root instead of in a subdirectory called `lambda` (like what is created with `-t lambda` ☝️ ) -- now I'm getting a new strange error where my code is working in Lambda, but in `docker-lambda`, I get:
```
START RequestId: 1b57a15a-5d37-40cc-9162-98657da0cea2 Version: $LATEST
Unable to parse input as json: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


{"stackTrace": [["/usr/lib64/python2.7/json/__init__.py", 339, "loads", "return _default_decoder.decode(s)"], ["/usr/lib64/python2.7/json/decoder.py", 364, "decode", "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"], ["/usr/lib64/python2.7/json/decoder.py", 382, "raw_decode", "raise ValueError(\"No JSON object could be decoded\")"]], "errorType": "ValueError", "errorMessage": "No JSON object could be decoded"}
END RequestId: 1b57a15a-5d37-40cc-9162-98657da0cea2
REPORT RequestId: 1b57a15a-5d37-40cc-9162-98657da0cea2 Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 14 MB
```

**Comment by mhart** [comment]
Can you show me how you're invoking docker-lambda?

**Comment by holajoyce** [comment]
I've tried to run the lambda in the unzipped directory structured as mentioned above, but I get an error like this
"cannot import name LifoQueue" causing the handler file not to load

**Comment by AlecBenzer** [comment]
Having the exact same issue, command:

```shell
docker run --rm -v <redacted>:/var/task:z lambci/lambda:python3.6 python3.6 -m pip --isolated install -t .serverless/requirements -r .serverless/requirements.txt
```

(via [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements))

**Comment by mhart** [comment]
@AlecBenzer shouldn't you be using the build image if you're trying to install requirements?

**Comment by mhart** [comment]
@tathagata you should be using one of the build images

**Comment by tathagata** [comment]
Of course ... written clearly in the readme! thanks for pointing out.
So anytime the lambda depends on other packages (i.e. a requirments.txt), we would have to use the build image?

**Comment by mhart** [comment]
@tathagata the normal images are for executing lambdas (ie, testing them) – so you're right: any building/installing/deploying/etc, use the build images.

**Comment by tathagata** [comment]
@mhart thanks a lot for the reply. 
One thing is not being very obvious from the docs, say I use a build image to create a new lambda which needs external packages. I let the Dockerfile take care of the package installations via pip install.
After that, when the new image is created, how do I invoke the lambda in this container for testing if the code is working fine?

```
docker build -t lambdafunc .
docker run --rm  lambdafunc
```
gives me 

```
zip I/O error: Permission denied
zip error: Could not create output file (lambdafunc.zip)
```

Or am I viewing the workflow incorrectly - my objective is to test the lambda locally till iron out the kinks.
Thanks once again for such quick replies.
