### ISSUE TITLE
identical to lambda?

### ISSUE THREAD

**Issue by tommedema** [lambci/docker-lambda#58]
I figured that if I could run certain commands inside a docker container based on docker-lambda, I must also be able to run these commands on lambda itself. This does not seem to be the case for the following:

This works (docker):

```
docker run -v "$PWD":/var/task -it lambci/lambda:build bash
easy_install pip
pip install -U certbot
```

This does not work (lambda):

```
./lambdash easy_install pip && pip install -U certbot
```

Results in `/bin/sh: easy_install: command not found`, while it works just fine with `docker-lambda`.

**Comment by mhart** [comment]
That's because you're using the build image – which [has a lot more installed on it](https://github.com/lambci/docker-lambda/blob/master/base/build/Dockerfile).

Try running the same command with the `python2.7` or `python3.6` image

**Comment by tommedema** [comment]
@mhart that makes a lot of sense, thanks!

is it still possible for me to run bash inside this container? When I try it I get

```
Toms-MBP-2:lambdash tommedema$ docker run -v "$PWD":/var/task -it lambci/lambda:python3.6 bash
Unable to find image 'lambci/lambda:python3.6' locally
python3.6: Pulling from lambci/lambda
5aed7bd8313c: Already exists 
d60049111ce7: Already exists 
216518d5352c: Pull complete 
47aa6025d0bc: Pull complete 
9a82bb1662ac: Pull complete 
Digest: sha256:3663b89bd1f4c4d1a4f06a77fc543422c1f0cbfc3a2f491c8c7bdc98cf9cf0b6
Status: Downloaded newer image for lambci/lambda:python3.6
START RequestId: 05edcbae-16f1-41f9-b9c2-eec21f24d71b Version: $LATEST
Bad handler 'bash': not enough values to unpack (expected 2, got 1)
END RequestId: 05edcbae-16f1-41f9-b9c2-eec21f24d71b
REPORT RequestId: 05edcbae-16f1-41f9-b9c2-eec21f24d71b Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 18 MB

{"errorMessage": "Bad handler 'bash'"}
```

**Comment by mhart** [comment]
Ah yeah, that's because the non-build images set an explicit docker entrypoint (so you can run lambda functions directly from the command line). You just need to override the entrypoint:

```console
docker run -v "$PWD":/var/task --entrypoint bash -it lambci/lambda:python3.6
```

Now you'll notice that the python3.6 image (and lambda) *does* have `easy_install` (in `/var/lang/bin/easy_install` – also in the lambda PATH) – but the python2.7 lambda does not. This should match the live Lambda behavior for these runtimes – if it doesn't, please feel free to file another issue.
