### ISSUE TITLE
AWS SAM lambda runtimes

### ISSUE THREAD

**Issue by mariusgrigaitis** [lambci/docker-lambda#59]
I just found out http://docs.aws.amazon.com/lambda/latest/dg/test-sam-local.html

It seems to come with lambda docker runtimes. Has anyone looked deeper into it? Maybe it would make sense to replace current runtimes into that one in the future?

**Comment by mariusgrigaitis** [comment]
Looks like it's using runtimes from this project?

2017/12/05 12:01:52 Fetching lambci/lambda:python3.6 image for python3.6 runtime...

**Comment by mhart** [comment]
Yes, it does – AWS chose it because it was the closest reproduction to production lambda!
