### ISSUE TITLE
How to leverage caching?

### ISSUE THREAD

**Issue by josegonzalez** [lambci/docker-lambda#6]
I'd love to be able to cache compiled python wheels so we don't have to hit the network/recompile unnecessarily. My current command is as follows:

```
mkdir -m 777 -p ../.cache
docker run --rm \
    -v "$PWD/../.cache":/tmp/.cache \
    -v "$PWD":/var/task \
    lambci/lambda:build-python2.7 pip install -r requirements.txt --cache-dir /tmp/.cache -vv -t env
```

Unfortunately, I get the following error:

```
The directory '/tmp/.cache/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/tmp/.cache' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

Any idea as to what I can do here to mount a cache directory from the OS properly within the docker container?

**Comment by mhart** [comment]
If you're using the build image, then why not just put the cache directory in the current directory and save the extra `-v` call? Does that work for you?

**Comment by mhart** [comment]
Btw – this sounds like a `pip` error? Like, because it's being executed by root. Is there not some pip configuration you can change to ignore that error?

Other ppl run into similar issues in Docker here: https://github.com/pypa/pip/issues/3596

**Comment by josegonzalez** [comment]
```
$ docker run --rm -v "$PWD":/var/task lambci/lambda:build-python2.7 pip install -r requirements.txt --cache-dir /var/task/.cache -t env
The directory '/var/task/.cache/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/var/task/.cache' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

**Comment by mhart** [comment]
A few other things I could suggest:

1. Try a different directory that's not `/tmp` or `/var/task` – like `/root/.cache`
2. Change ownership of the directory, like:
```
docker run --rm -v "$PWD":/var/task lambci/lambda:build-python2.7 bash -c \
  'chown -R root /var/task/.cache && pip install -r requirements.txt --cache-dir /var/task/.cache -t env'
```

**Comment by mhart** [comment]
And another thing I could suggest would be to setup a Dockerfile that uses lambci/lambda:build-python2.7 as a base and do your build in steps – that way you can leverage the caching that Docker layers provide you

**Comment by josegonzalez** [comment]
I have this which seems to work:

```
docker run --rm -v \"$PWD\":/var/task lambci/lambda:build-python2.7 bash -c \
    'rsync -a /var/task/.cache/ /root/.cache/ || true && chown -R root /root/.cache && pip install -r requirements.txt -t env && rsync -a /root/.cache/ /var/task/.cache/'
```

Not sure on how to make this more approachable, but definitely a step in the right direction!
