### ISSUE TITLE
Trying to install postgresql fails

### ISSUE THREAD

**Issue by nils2504** [lambci/docker-lambda#60]
Hi,

i try to use psycopg2 in python3.6 but i am still getting an error in Lambda.
The issue might be that there is no postgresql-devel installed on the docker linux vm.

But when i try to install i still get an error (neverless if i use the `yum -y update` or not)

```
FROM lambci/lambda:build-python3.6

RUN yum -y update \
    && yum install -y yum-plugin-ovl \
    && yum install -y postgresql-devel

CMD ["bash"]
```

Error is (with update):

> E: Failed to install umount
> mkinitrd failed
> warning: %posttrans(kernel-4.9.43-17.39.amzn1.x86_64) scriptlet failed, exit status 1
> Non-fatal POSTTRANS scriptlet failure in rpm package kernel-4.9.43-17.39.amzn1.x86_64

or without update:

> Rpmdb checksum is invalid: dCDPT(pkg checksums): postgresql92-libs.x86_64 0:9.2.22-1.61.amzn1 - u

**Comment by mhart** [comment]
You're probably running into a bug with overlayfs (nothing to do with `docker-lambda`).

See here for more info and workarounds:

https://github.com/moby/moby/issues/10180#issuecomment-252563599
Or
https://docs.oracle.com/cd/E52668_01/E69348/html/uek4-czc_xmc_xt.html
