### ISSUE TITLE
XRay not supported in lambda (Python2.7)

### ISSUE THREAD

**Issue by MarSoft** [lambci/docker-lambda#61]
Tried to use AWS XRay (via `aws_xray_sdk`) with `lambci/lambda:python2.7`. All I get regarding lambda is a warning: `Subsegment ... is discarded due to Lambda worker still initializing`.
After some debugging into Lambda code, looks like the reason is `_GLOBAL_XRAY_TRACE_ID = None` `runtime-mock.py`.
Probably it should be set to something more relevant, or at least make it possible to set this value via environment variables. AFAIR it should have the following format: `Root=TRACE_ID;Parent=ENTITY_ID;Sampled=<0|1>`.

**Comment by mhart** [comment]
I committed a change that *should* work – if the other variables need setting, let me know – but this is at least one that exists in the environment on Lambda itself – and should let you override it.
