### ISSUE TITLE
"argument list too long" when passing a large custom event

### ISSUE THREAD

**Issue by shinichy** [lambci/docker-lambda#64]
I debugged https://github.com/awslabs/aws-sam-local/issues/188 and found that a large binary data is passed as a body like below and it causes `argument list too long` error.

```
{"httpMethod":"POST","body":"<large data>","resource":"/","requestContext":{"resourcePath":"/","httpMethod":"POST","stage":"prod","identity":{"sourceIp":"127.0.0.1:49921"}},"queryStringParameters":{},"headers":{"Accept":"*/*","Content-Length":"128680","Content-Type":"application/x-www-form-urlencoded","Expect":"100-continue","User-Agent":"curl/7.54.0"},"pathParameters":null,"stageVariables":null,"path":"/"}
```

Is there a way to pass a large custom event?

**Comment by mhart** [comment]
Yes, you can use the `AWS_LAMBDA_EVENT_BODY` env variable instead of passing over the command line

**Comment by mhart** [comment]
See https://github.com/lambci/docker-lambda/blob/master/nodejs6.10/run/awslambda-mock.js#L4 for details

**Comment by shinichy** [comment]
I tried AWS_LAMBDA_EVENT_BODY but still I get the same error.
Looks like both command line argument and env variable have the same limitation.
https://stackoverflow.com/questions/28865473/setting-environment-variable-to-a-large-value-argument-list-too-long

I think docker-lambda needs an option to read from stdin or a file for a large json.

index.js
```
exports.handler = function(event, context, cb) {
	console.log(event)
  cb()
}
```

Generate a large json and run with it
```
LARGE_DATA=`printf 'a%.0s' {1..500000}`; LARGE_JSON="{\"body\": \"$LARGE_DATA\"}"; docker run -v "$PWD":/var/task -e AWS_LAMBDA_EVENT_BODY=$LARGE_JSON lambci/lambda index.handler
```

**Comment by FranciscoHanna** [comment]
@mhart How I pass data using that env variable? I'm facing this same issue running my lambda function + API locally. It works when deployed though.

**Comment by shinichy** [comment]
@mhart Great! Thank you!!
