### ISSUE TITLE
Go support

### ISSUE THREAD

**Issue by rgarcia** [lambci/docker-lambda#65]
https://aws.amazon.com/blogs/compute/announcing-go-support-for-aws-lambda/

**Comment by mhart** [comment]
Yup, been working on it for the last week: https://twitter.com/hichaelmart/status/953085798680756225

**Comment by andrzejsliwa** [comment]
@mhart any updates here? maybe you can make PR with work in progress.

**Comment by brettneese** [comment]
@mhart please do let us know if you need any help! :)

**Comment by mhart** [comment]
PR is here, still to add build image: #67

**Comment by brettneese** [comment]
Looks like this got shipped! 🚀♥️

**Comment by mhart** [comment]
Oh yeah – closing!
