### ISSUE TITLE
Reading from console.log using NPM module

### ISSUE THREAD

**Issue by irvinlim** [lambci/docker-lambda#69]
Hi, first of all thanks for the awesome package and Docker image! I'm currently using it in [es2017-lambda-boilerplate](https://github.com/irvinlim/es2017-lambda-boilerplate) for running automated tests within a Lambda environment itself.

I noticed that `console.log` statements are captured in [`awslambda-mock.js`](https://github.com/lambci/docker-lambda/blob/master/nodejs6.10/run/awslambda-mock.js#L16), where it is written to `stderr`. This is great when running the Docker image using `docker run`.

However, since I am using the NPM module, there is no way for me to access the contents of `stderr` from calling `dockerLambda()`, if the execution is successful.

Could you add a way for us to access `stderr`, perhaps by passing a callback function, or returning an object like `{ stdout: ..., stderr: ...}` when an option is set? What do you think is the best way to support this?

**Comment by mhart** [comment]
Check the `returnSpawnResult` option – that's probably what you want: https://github.com/lambci/docker-lambda/blob/master/index.js#L30

Set that to `true` and then you have access to `spawnResult.stderr`, etc

**Comment by irvinlim** [comment]
Oh yes, that option does the trick! Thank you :)
