### ISSUE TITLE
Running hooked up to a local kinesis stream

### ISSUE THREAD

**Issue by justinmchase** [lambci/docker-lambda#7]
I have a local kinesis stream running in docker for testing purposes. I want to make a lambda function that is called when events come through that stream.

From looking at your code here I could pretty easily use your docker image that runs a little harness that hooks up to kinesis then forwards messages into my lambda function using your library. Does that sound right?

Do you know if there is already a tool to help with this? I don't want to re-invent the wheel here if I can avoid it.

**Comment by mhart** [comment]
No, there's no tool that I know of, but that all sounds like a reasonable plan – you'll just need to get the kinesis event in the right format to be consumed by the lambda function.

I assume that AWS uses the [KCL](http://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-kcl.html) internally to consume kinesis events and publish them to lambda, so it might be worth using that as part of your glue.
