### ISSUE TITLE
Spawning persistent sub-processes

### ISSUE THREAD

**Issue by der-flo** [lambci/docker-lambda#72]
I'm actually working on a advanced Ruby-Lambda-bridge and facing a central problem. Spawned processes seem to block the invocation. I use `child_process.spawn()` in combination with pipes because bigger Ruby application need to kept warmed up regarding larger startup times.

I have reduced the problem to a simple example:
```javascript
const spawn = require('child_process').spawn;
const rubyProcess = spawn("bash", ["-c", "while true; do sleep 0.2; done"])
exports.handler = function(event, context, callback) {
   callback(null, {foo: "bar"})
}
```
I'm seeing this effect not only with your docker image but also with the production lambda. Documentation on this aspect of lambda is very basic, a [blog article around this topic](https://aws.amazon.com/de/blogs/compute/container-reuse-in-lambda/) doesn't help me that much.

**Comment by mhart** [comment]
I'm not sure what your exact issue is?

Each (production) Lambda invocation will only handle a single process, with a synchronous request cycle. When the request is over, Lambda will freeze the "container", waking it again on the next invocation (served from that Lambda). Concurrent Lambdas are completely isolated from each other.

**Comment by mhart** [comment]
To clarify:

> will only handle a single process

I mean it will only handle a single Lambda process – obviously your Lambda can spawn multiple subprocesses if it wants.

**Comment by der-flo** [comment]
Grrr, I missed a simple thing:

```javascript
context.callbackWaitsForEmptyEventLoop = false
```
That allows the callback/invocation to finish but leave the Lambda process and subprocesses freezed.

My remaining problems are already documented in #14.
