### ISSUE TITLE
How often are images updated?

### ISSUE THREAD

**Issue by learley** [lambci/docker-lambda#73]
I am using the lambci/lambda:nodejs6.10 image by way of [AWS SAM Local](https://github.com/awslabs/aws-sam-local). I ran into an issue today while testing a function that I eventually discovered was due to a discrepancy in AWS SDK for JavaScript versions between the docker image and the live Lambda environment. In this particular case, I was using a parameter that wasn't added until [v2.200.0](https://github.com/aws/aws-sdk-js/commit/9d1c09d4c403dcac6a30e695482dc7ac28807064#diff-0e08df84852e319e33cd9bd7ea389f5e) and when I ran it with SAM Local I got an 'Unexpected parameter' error on validation. However, it works in the Lambda service, which according the [documentation](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) has the latest SDK version bundled (v2.205.0).

I know this isn't exactly your problem but it lead me to wonder how often you update the images from the Lambda environment. SAM Local appears to pull the latest image from here each time it runs so I am not sure if I could build my own or not.

```2018/03/23 16:34:12 Successfully parsed template.yaml
2018/03/23 16:34:12 Connected to Docker 1.35
2018/03/23 16:34:13 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:bc47c223a2accf47c51adc6e1949bda9b557764be38a76ebac73e545044079cc
Status: Image is up to date for lambci/lambda:nodejs6.10
```

Thanks for any help or advice.

**Comment by mhart** [comment]
Hi @learley – yeah, this is a problem. I update the images whenever AWS tell me they've updated something or I see a release document go out or similar.

I'll update the images when I get the chance, and hassle AWS about communicating these changes to me in some sort of regular way.

**Comment by learley** [comment]
@mhart - I appreciate the quick response. Thank you for your efforts.

**Comment by mhart** [comment]
Completed in 81c9d6cd6aa8862025aa6eef1208088245d3c25f
