### ISSUE TITLE
Node 8.10

### ISSUE THREAD

**Issue by tdmalone** [lambci/docker-lambda#74]
Firstly, THANK YOU for all the work you have done putting together these images. It's a massive timesaver and really, a joy to use.

This post excites me:
https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

And while I know it was only posted today, I thought I'd start an issue because I'd _love_ to see the new runtime in docker-lambda.

I'm not entirely sure what is involved, but if there's anything I can help with, let me know.

**Comment by lmammino** [comment]
I'd love to see this soon as well (actually I just opened a similar issue on SAM Local: https://github.com/awslabs/aws-sam-local/issues/343), so let me know if there's anything I can help with!

**Comment by mhart** [comment]
Completed in 81c9d6cd6aa8862025aa6eef1208088245d3c25f – test it out now!

**Comment by lmammino** [comment]
This was fast, thanks @mhart!
