### ISSUE TITLE
[Win 10] Class Not Found Exception When Trying to run example Java code provided. What am I doing wrong?

### ISSUE THREAD

**Issue by mongoDynamo** [lambci/docker-lambda#77]
![image](https://user-images.githubusercontent.com/38298138/38998644-05885a0e-43be-11e8-89f9-eb2807cd3b32.png)

**Comment by mhart** [comment]
I'm guessing you ran `gradle build` first?

Are you on Windows? I've never tested it on Windows and have no idea how docker works on Windows. You might need to drop into an interactive shell and see whether the paths are correct.

**Comment by mongoDynamo** [comment]
@mhart Yeah, I did. 

I ended up getting it to work with my lambda function but in a weird way. I can't use single quotes around my JSON, it will cause it to fail on Jackson for saying simple type can't be converted to my custom POJO.

![image](https://user-images.githubusercontent.com/38298138/39000136-44e8d914-43c1-11e8-9b47-9745f4407d5c.png)


If I don't use the single quote it fails saying it was expecting true for my title entity, no clue why. 

![image](https://user-images.githubusercontent.com/38298138/39000163-535c36c6-43c1-11e8-9d07-890b005ee874.png)

So if I replace the title with 'true', my lambda function works as expected. 

![image](https://user-images.githubusercontent.com/38298138/39000212-6f3000bc-43c1-11e8-82fc-c5551795ac21.png)


Any advice as to what I should do to allow any JSON as input? Could I use a file as input? Maybe that'll be easier to gauge.

**Comment by mhart** [comment]
I think you just need to escape the input correctly for the shell you're using – no idea why it doesn't support single quotes.

Perhaps just try:

```
"{\"key\": \"value\"}"
```

**Comment by mongoDynamo** [comment]
@mhart Thanks for that. It does work. 

Is there a way to use a file with this? I guess I could cat a file into a variable to be used, but is there a better way?

**Comment by mhart** [comment]
Yeah, there's an example on the README

**Comment by mongoDynamo** [comment]
@mhart Hey, sorry to bother you, but could you link me the readme, and or tell me what line its mentioned? I read through the readme and could only find mention of using a handler through a file, not a text or json file as input into the function as opposed to a custom string.

**Comment by mhart** [comment]
End of the first example block:

```
# For large events you can pipe them into stdin if you set DOCKER_LAMBDA_USE_STDIN (on any runtime)
echo '{"some": "event"}' | docker run --rm -v "$PWD":/var/task -i -e DOCKER_LAMBDA_USE_STDIN=1 lambci/lambda:nodejs8.10
```

So you could do:

```
docker run ... -e DOCKER_LAMBDA_USE_STDIN=1 ... < myfile
```

Or 

```
cat myfile | docker run ... -e DOCKER_LAMBDA_USE_STDIN=1 ...
```

Or whatever you want...
