### ISSUE TITLE
Getting HTTP connection refused when trying to interact with localstack endpoint. Can docker-lambda work with localstack's AWS endpoints? 

### ISSUE THREAD

**Issue by mongoDynamo** [lambci/docker-lambda#78]
Any way to use my lambda with localstack endpoint? I already tested the function in my IDE and it does communicate with localstacks endpoint correctly. But when trying to run through docker-lambda I get a connection refused error. Anything I can do to make this work with localstack's mock endpoints?

![image](https://user-images.githubusercontent.com/38298138/39001053-651bf584-43c3-11e8-88af-ee3a73a8e277.png)

**Comment by mongoDynamo** [comment]
I tried linking my localstack docker network when running the docker lambda and I still get the same HTTP connection refused message. 
![image](https://user-images.githubusercontent.com/38298138/39001509-6d7b5a34-43c4-11e8-9877-6a90c2aa13b0.png)

**Comment by mhart** [comment]
@mongoDynamo networking questions like these are things you should issue to the docker forums or similar – these issues are for bugs in docker-lambda

**Comment by mongoDynamo** [comment]
@mhart Ok, sorry about that. Just got excited to see that docker-lambda doesn't throw random compilation problems like localstack, and I was hoping to see how I could get past this network issue. 

Thanks for the help, and sorry for asking this in the wrong place.

**Comment by mhart** [comment]
No probs, you might find your issue at localstack too: https://github.com/localstack/localstack/issues/27#issuecomment-298964660

**Comment by mongoDynamo** [comment]
@mhart I figured it out. The work around was so simple, I just had to execute the lambda function on the same ip as localstack, which is easy as its localhost. So I just had to run docker-lambda with the --net="host"

![image](https://user-images.githubusercontent.com/38298138/39002762-403d7b30-43c7-11e8-978b-d142fc036910.png)
