### ISSUE TITLE
Unable to import module 'lambda_function' (yet again)

### ISSUE THREAD

**Issue by czechnology** [lambci/docker-lambda#83]
Just as some other reported before me, I am also struggling with the "unable to import module" error.

I'm trying to run the Python 3.6 container. I am executing in a Mintu VM on Win10. I had the same issues in Win10 WSL but I assumed it might be due to the problematic mapping between the WSL and docker paths on Windows.

I tried following:

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24
$ echo "$PWD"
/media/sf_vm_share/my_lambda
$ ls
data
lambda_function.py
my_module.py
$ ls "$PWD"
data
lambda_function.py
my_module.py
$ docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6
START RequestId: 01a6b5fe-646e-4bd3-8d30-fbfe1173407f Version: $LATEST
Unable to import module 'lambda_function': No module named 'lambda_function'
END RequestId: 01a6b5fe-646e-4bd3-8d30-fbfe1173407f
REPORT RequestId: 01a6b5fe-646e-4bd3-8d30-fbfe1173407f Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 19 MB

{"errorMessage": "Unable to import module 'lambda_function'"}
$ docker run --rm -v "$PWD":/var/task lambci/lambda:python3.6 my_module.my_handler
START RequestId: a51dbe88-490e-42bd-97d6-2faadb7e8ed2 Version: $LATEST
Unable to import module 'my_module': No module named 'my_module'
END RequestId: a51dbe88-490e-42bd-97d6-2faadb7e8ed2
REPORT RequestId: a51dbe88-490e-42bd-97d6-2faadb7e8ed2 Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 19 MB

{"errorMessage": "Unable to import module 'my_module'"}
```

What am I doing wrong? If I run the build-python3.6 image with bash and do `ls`, I can see the files correctly in the directory.

Thanks for any hints!

**Comment by ozskywalker** [comment]
I was not able to reproduce this... could you try running `docker run` again but _without `--rm`_, then perform a `docker inspect` against the container and post both the contents here of `docker inspect` & `my_module.py` ?

**Comment by czechnology** [comment]
I'm now struggling to reproduce this now too... Was probably caused by permission issues on the VirtualBox shared directory (gee, I wish I could work on native linux).
I'll get back to you if I isolate the problem. Sorry about that!
