### ISSUE TITLE
OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by aburkov** [lambci/docker-lambda#84]
Hi. During the execution of the following line in the Dockerfile:

`RUN pip install -r requirements.txt -t /var/task/lib`

I get the following error:

```
Step 15/15 : RUN pip install -r requirements.txt -t /var/task/lib
 ---> Running in dcbdc1ea5e34
Collecting rtree==0.7.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a5/af/0811b3cb141f425ca5090b7d9fa5cd6a9e93eeb6d194f11a89f1cc619642/Rtree-0.7.0.tar.gz (44kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2_CnRK/rtree/setup.py", line 5, in <module>
        import rtree
      File "rtree/__init__.py", line 1, in <module>
        from index import Rtree
      File "rtree/index.py", line 2, in <module>
        import core
      File "rtree/core.py", line 85, in <module>
        rt = ctypes.CDLL(lib_name)
      File "/usr/lib64/python2.7/ctypes/__init__.py", line 357, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/libspatialindex/libspatialindex_c.so)
```

I have built "libspatialindex_c.so" myself using the original Amazon Linux (amzn2-virtualbox-2017.12.0.20180330-x86_64.xfs.gpt) in VirtualBox.

I'm confused. Whether I'm missing something or "GLIBCXX_3.4.21" is missing in docker-lambda?

If docker-lambda indeed should have "GLIBCXX_3.4.21", how can I install it?

**Comment by mhart** [comment]
Sounds like a glibc mismatch in your compiled library. For things like this you're best off building the native library either using the build images from this repository, or the Amazon Linux version which matches Lambda (2017.03)
