### ISSUE TITLE
No c++ compiler found on docker-lambda

### ISSUE THREAD

**Issue by aburkov** [lambci/docker-lambda#85]
The README says "You can also use it to compile native dependencies knowing that you're linking to the same library versions that exist on AWS Lambda and then deploy using the AWS CLI."

I try to compile libspatialindex

```
RUN curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz
WORKDIR $APP_DIR/tmp/spatialindex-src-1.8.5
RUN ./configure
RUN make
RUN sudo make install
RUN sudo ldconfig
```

and get the error that there's no C++ compiler:

```
checking build system type... x86_64-unknown-linux-gnu
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether the C++ compiler works... no
configure: error: in `/var/task/tmp/spatialindex-src-1.8.5':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
ERROR: Service 'lambda' failed to build: The command '/bin/sh -c ./configure' returned a non-zero code: 77
make: *** [docker-build] Error 1
```

Do I miss something? How can I get a native library compiled for Lambda using docker-lambda?

**Comment by mhart** [comment]
@aburkov which image are you using?

**Comment by aburkov** [comment]
lambci/lambda:python2.7

**Comment by mhart** [comment]
Please read the README in more detail:

> There are also a set of build images that include packages like gcc-c++, git, zip and the aws-cli for compiling and deploying.

You can see some examples of using the build images about halfway down the [Example](https://github.com/lambci/docker-lambda#example) section
