### ISSUE TITLE
How to copy a binary after it was built using build-python2.7 image?

### ISSUE THREAD

**Issue by aburkov** [lambci/docker-lambda#86]
Hi, again. I managed to build my binaries using build-python2.7 image:

Successfully built 4fd57f4fe2cc
Successfully tagged website_tester_lambda:latest

Now I would like to copy them to my host's hard drive, build a zip and upload to AWS. How can I copy this binary from docker to the host machine's hard drive?

I checked the README and examples again and didn't find how to do that.

**Comment by aburkov** [comment]
I think I found a solution:

First start container and run some command that keeps container running:

docker run -i -t website_tester_lambda:latest /bin/bash

Then in another terminal window execute:

docker cp <containerId>:/file/path/within/container /host/path/target

Is there a simpler path?

**Comment by mhart** [comment]
@aburkov the `aws` command line is installed on the build images, so you can just upload/deploy straight from there.

If you don't want to do that, then either `docker cp` or just mount your local directory in the docker image and build to it (using the `-v` flag). Best to look at Docker documentation for how to manage things like that.

**Comment by mhart** [comment]
(you don't need to keep the container running to use `docker cp` by the way – you just have to not remove it when you run it (ie, *not* use the `--rm` flag). `docker ps -a` will show you containers that you've run in the past that have stopped)
