### ISSUE TITLE
{"errorMessage": "Unable to import module 'lambda_function'"}

### ISSUE THREAD

**Issue by jeremyzhou** [lambci/docker-lambda#89]
1.	follow the AWS Guide https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html
2.	cd  D:\cloud
3.	zip D:\cloud.zip *
4.	add C:\Python27\Lib\site-packages\* to cloud.zip
5.     put the zip package to /home/jlzhou/cloud/
6.     but Unable to import module 'lambda_function': No module named lambda_function

[root@localhost cloud]# **docker run --rm -v /home/jlzhou/cloud/:/var/task  docker.io/lambci/lambda:python2.7**
Unable to find image 'docker.io/lambci/lambda:python2.7' locally
Trying to pull repository docker.io/lambci/lambda ... 
python2.7: Pulling from docker.io/lambci/lambda
5be106c3813f: Already exists 
e240967675e1: Already exists 
8204f2804dc9: Pull complete 
542dd953e06d: Pull complete 
5415c01e5b50: Pull complete 
Digest: sha256:d35515d2938a5b7f24cba04d0034a37ebe0288602947a0d50828638538f4ad90
Status: Downloaded newer image for docker.io/lambci/lambda:python2.7
START RequestId: c9a6623d-5579-4887-98ce-7d1a31aa7c95 Version: $LATEST
**Unable to import module 'lambda_function': No module named lambda_function
END RequestId: c9a6623d-5579-4887-98ce-7d1a31aa7c95
REPORT RequestId: c9a6623d-5579-4887-98ce-7d1a31aa7c95 Duration: 0 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 11 MB

{"errorMessage": "Unable to import module 'lambda_function'"}**

**Comment by mhart** [comment]
@jeremyzhou what is your module called? By default it will look for a file named `lambda_function.py` containing a function called `lambda_handler`.

See this example: https://github.com/lambci/docker-lambda/blob/master/examples/python/lambda_function.py

**Comment by jeremyzhou** [comment]
@mhart Thanks, I had solve the problem.
1.do not zip the package.
2.Upload the lamda_fuction.py and depency package to  /home/jlzhou/cloud/
3.It works!

docker run --rm -v /home/jlzhou/cloud/create_network/:/var/task  --env "MONGO_DB_NAME=test MONGO_USER=jeremy MONGO_PASSWORD=123 MONGO_HOST=10.103.55.251" docker.io/lambci/lambda:python2.7 lambda_function.create_network 
START RequestId: 3160ec8e-dc9f-4784-8994-62f2ebf4d22c Version: $LATEST

{"body": "{\"message\": \"OrgId Is Invalid\", \"code\": 400}", "headers": {"Access-Control-Allow-Methods": "GET, DELETE, PATCH, POST", "Access-Control-Allow-Headers": "content-type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token", "Content-Type": "application/json", "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Credentials": true}, "statusCode": 400}
END RequestId: 3160ec8e-dc9f-4784-8994-62f2ebf4d22c
REPORT RequestId: 3160ec8e-dc9f-4784-8994-62f2ebf4d22c Duration: 305 ms Billed Duration: 400 ms Memory Size: 1536 MB Max Memory Used: 16 MB

**Comment by mhart** [comment]
Great! Also, be sure to check out AWS SAM and AWS SAM CLI: https://github.com/awslabs/aws-sam-cli#invoke-functions-locally – they might make things a bit easier for you (maybe).

**Comment by jeremyzhou** [comment]
@mhart One more question:

One lambda function have a directory include a lambda_function.py and dependent libraries.
30 lambda functions have 30 directory include it’s lambda_function.py and 30 copies dependent libraries.
![image](https://user-images.githubusercontent.com/6510252/41010970-0d8e14ee-696d-11e8-9cc9-539403e933d8.png)

Use “du -h” to see the size of packages
404K ./update_device_config/urllib3-1.22-py2.7.egg/urllib3
488K ./update_device_config/urllib3-1.22-py2.7.egg
69M  ./update_device_config
**3.0G .**
[root@localhost cloud]

Is there any better solution? Can lambda calls subdirectory lambda_function method?
