### ISSUE TITLE
Java test runners is not complete

### ISSUE THREAD

**Issue by asyazwan** [lambci/docker-lambda#9]
Trying to run a basic hello world python lambda:

`docker run -v "$PWD":/var/task lambci/lambda:python2.7`

yields:

```
recv_start
Traceback (most recent call last):
  File "/var/runtime/awslambda/bootstrap.py", line 364, in <module>
    main()
  File "/var/runtime/awslambda/bootstrap.py", line 344, in main
    (invokeid, mode, handler, suppress_init, credentials) = wait_for_start(int(ctrl_sock))
  File "/var/runtime/awslambda/bootstrap.py", line 135, in wait_for_start
    (invokeid, mode, handler, suppress_init, credentials) = lambda_runtime.recv_start(ctrl_sock)
  File "/var/runtime/awslambda/runtime.py", line 13, in recv_start
    return (invokeid, mode, handler, suppress_init, credentials)
NameError: global name 'invokeid' is not defined
```

**Comment by mhart** [comment]
Right 😁

https://github.com/lambci/docker-lambda/blob/master/python2.7/run/runtime-mock.py#L7

**Comment by mhart** [comment]
It says [on the README](https://github.com/lambci/docker-lambda#docker-lambda), "Python 2.7 and Java 8 test runners are not yet complete, but both languages are installed in the images so can be manually tested"

I haven't really had the time to dig into how the Python and Java runners in Lambda differ from the Node.js one – the Python one appears to use more HTTP functionality to communicate with the AWS Lambda coordinator than Node.js does, but I really haven't looked into it deeply.

I'd happily accept a PR from anyone who's looked into it and can replicate the existing functionality of the Node.js wrapper

**Comment by lvh** [comment]
@mhart I'd like to look into this more. Where did that runtime-mock.py file come from?

**Comment by lvh** [comment]
(Also, perhaps there should be two tickets; the Java and Python problems seem distinct.)

**Comment by mhart** [comment]
@lvh I just created it. Based on the contents of `/var/runtime/awslambda/bootstrap.py` and reverse engineering the interface being used

**Comment by lvh** [comment]
It seems like invokeid might be what the [Python Lambda docs][ctxobj] call `aws_request_id`. Looks like for testing purposes it's OK if that's just a constant (or perhaps a random) string?

[ctxobj]: http://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html

**Comment by mhart** [comment]
@lvh yep, spot on – that's exactly what I do for Node.js: https://github.com/lambci/docker-lambda/blob/master/nodejs/run/awslambda-mock.js#L45

**Comment by lvh** [comment]
Cool. I'm working on this. Do you recall what the point was of rebinding `sys.std{out,err}`?

**Comment by mhart** [comment]
@lvh I believe it's Lambda itself that overrides them (ie, `bootstrap.py`, which comes from Lambda). I believe it overrides them to send logs remotely. Whereas, for mocking purposes, we don't want them overridden, so we restore them to the originals on function invocation.

**Comment by endemics** [comment]
@lvh I was looking for a fork where you would have published your work but couldn't find it, so I ended up implementing it instead in #15. Sorry if there was duplicated work. Your feedback on my PR is very welcome!

**Comment by mhart** [comment]
Just commenting here to say the Python 2.7 implementation started by @endemics has been merged now – so I've updated the title accordingly

**Comment by mhart** [comment]
Actually, there's already an issue tracking Java support: #1 – so I'll close this one
