### ISSUE TITLE
Docker run failing in ubuntu

### ISSUE THREAD

**Issue by slsumathi** [lambci/docker-lambda#91]
Here is the error log

sagar@SagarPC:~$ sudo docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10
Unable to find image 'lambci/lambda:nodejs8.10' locally
nodejs8.10: Pulling from lambci/lambda
5be106c3813f: Already exists 
e240967675e1: Already exists 
9a0b2a03ec1a: Pull complete 
6d29ce82f2d9: Pull complete 
Digest: sha256:0bb86ceaeebc3023f59b0fb9f0c22490eb55a11d9ad133363ef57f04c01766ba
Status: Downloaded newer image for lambci/lambda:nodejs8.10
START RequestId: eddbbb25-798a-129d-724b-e42791000b0b Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: eddbbb25-798a-129d-724b-e42791000b0b
REPORT RequestId: eddbbb25-798a-129d-724b-e42791000b0b	Duration: 3.76 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 33 MB	

{"errorMessage":"Cannot find module '/var/task/index'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}
sagar@SagarPC:~$

**Comment by mhart** [comment]
That's not failing to run. Do you have an `index.js` in your directory? Please read the README and see the examples for more details
