### ISSUE TITLE
Selenium module not installing correctly with lambci/lambda:build-python3.6

### ISSUE THREAD

**Issue by S-Cardenas** [lambci/docker-lambda#95]
Attempting to install `selenium` using `lambci/lambda:python3.6` installs the selenium package and all of its files and folders correctly. However, attempting to install with `lambci/lambda:build-python3.6` results in missing files and folders.

command:
`docker run -v $$PWD:/var/task lambci/lambda:build-python3.6 /bin/bash -c 'make _install_deps"'`

makeFile:
```
_install_deps:
	$(info [+] Installing '$(SERVICE)' dependencies...")	
	@pip3 install pipenv
	@pipenv lock -r > requirements.txt
	@pipenv run pip3 install \
		--isolated \
		--disable-pip-version-check \
		-Ur requirements.txt -t ${SERVICE}/build/
```

Pipfile
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
boto3 = "*"
requests = "*"
selenium = "*"

[dev-packages]
pytest = "*"
pytest-cov = "*"
```

Using `lambda:build-python3.6` results in the following folders & files:
<img width="202" alt="screen shot 2018-06-13 at 4 29 04 pm" src="https://user-images.githubusercontent.com/14102289/41379608-07ca0bec-6f28-11e8-9183-4e92cfbd21e7.png">

Using `lambda:python3.6` results in the correct folders & files:
<img width="225" alt="screen shot 2018-06-13 at 4 30 38 pm" src="https://user-images.githubusercontent.com/14102289/41379636-17621996-6f28-11e8-999a-f321c52c6cb0.png">

Notices that the majority of folders under `selenium/webdriver` are missing when installed with `lambda:build-python3.6`.

Any ideas?

**Comment by mhart** [comment]
No idea.

This seems kinda specific to `selenium` – are there no warnings or messages or anything that might indicate what happened? Is there a verbose mode you can enable?

Perhaps the command died halfway through the installation?

Have you tried running each command by itself in a bash session? Maybe that will give more info?

**Comment by S-Cardenas** [comment]
I actually figured out that part of the problem came from installing via `pipenv run pip3 install -Ur requirements.txt` instead of just plain `pip3 install -Ur requirements.txt`. Pipenv must be doing something behind the scenes which prevents all of the files/folders of the selenium package from installing.

Regardless, even if I do `pip3 install -Ur requirements.txt` there is still a discrepancy between `lambci/lambda:python3.6` and `lambci/lambda:build-python3.6`. The `build` version of the container doesn't install the package entirely. Could you think of anything, native installed packages or something, that could be causing this error? I'd really like to get to the root of this as I am afraid it can show up in other python packages.

I'll also be opening an issue with the `Selenium` module to discuss the issue which comes up with using `pipenv run pip3 install` versus the standard `pip3 install`.

**Comment by S-Cardenas** [comment]
For reference here is the [issue](https://github.com/SeleniumHQ/selenium/issues/6022) raised in the Selenium repo.

**Comment by mhart** [comment]
@S-Cardenas it absolutely could be that there are dependencies of some kind already installed on the `build-python3.6` image that the install process is detecting. You could probably figure that out by looking at what's not installed and seeing if it's elsewhere on the filesystem?

**Comment by mhart** [comment]
Closing this as it doesn't seem to be docker-lambda specific
